const quizData = {
    gk: {
        title_en: "General Knowledge",
        title_hi: "सामान्य ज्ञान",
        sections: {
            1: [
                {
                    q_en: "Which is the largest organ in the human body?",
                    q_hi: "मानव शरीर का सबसे बड़ा अंग कौन सा है?",
                    options_en: ["Liver", "Heart", "Skin", "Brain"],
                    options_hi: ["यकृत", "हृदय", "त्वचा", "मस्तिष्क"],
                    answer: 2,
                    hint_en: "It covers your entire body.",
                    hint_hi: "यह आपके पूरे शरीर को ढकता है।",
                    explanation_en: "The skin is the largest organ of the body, covering about 2 square meters.",
                    explanation_hi: "त्वचा शरीर का सबसे बड़ा अंग है, जो लगभग 2 वर्ग मीटर को कवर करती है।",
                    difficulty: "easy"
                },
                {
                    q_en: "Who is known as the 'Iron Man of India'?",
                    q_hi: "भारत के 'लौह पुरुष' के रूप में किसे जाना जाता है?",
                    options_en: ["Mahatma Gandhi", "Jawaharlal Nehru", "Sardar Vallabhbhai Patel", "Subhash Chandra Bose"],
                    options_hi: ["महात्मा गांधी", "जवाहरलाल नेहरू", "सरदार वल्लभभाई पटेल", "सुभाष चंद्र बोस"],
                    answer: 2,
                    hint_en: "He was the first Deputy Prime Minister of India.",
                    hint_hi: "वे भारत के पहले उप प्रधानमंत्री थे।",
                    explanation_en: "Sardar Patel is called the Iron Man of India for his role in integrating princely states.",
                    explanation_hi: "रियासतों के एकीकरण में उनकी भूमिका के लिए सरदार पटेल को भारत का लौह पुरुष कहा जाता है।",
                    difficulty: "medium"
                },
                {
                    q_en: "What is the currency of Japan?",
                    q_hi: "जापान की मुद्रा क्या है?",
                    options_en: ["Yuan", "Yen", "Won", "Baht"],
                    options_hi: ["युआन", "येन", "वोन", "बहत"],
                    answer: 1,
                    hint_en: "It starts with 'Y'.",
                    hint_hi: "यह 'Y' से शुरू होता है।",
                    explanation_en: "The Yen is the official currency of Japan and the third most traded currency.",
                    explanation_hi: "येन जापान की आधिकारिक मुद्रा है और तीसरी सबसे अधिक कारोबार वाली मुद्रा है।",
                    difficulty: "easy"
                },
                {
                    q_en: "Identify this famous landmark:",
                    q_hi: "इस प्रसिद्ध स्थल को पहचानें:",
                    options_en: ["Eiffel Tower", "Taj Mahal", "Great Wall of China", "Statue of Liberty"],
                    options_hi: ["एफिल टॉवर", "ताज महल", "चीन की महान दीवार", "स्टैच्यू ऑफ लिबर्टी"],
                    answer: 1,
                    hint_en: "It is located in Agra, India.",
                    hint_hi: "यह आगरा, भारत में स्थित है।",
                    explanation_en: "The Taj Mahal is an ivory-white marble mausoleum on the right bank of the river Yamuna.",
                    explanation_hi: "ताजमहल यमुना नदी के दाहिने किनारे पर एक हाथीदांत-सफेद संगमरमर का मकबरा है।",
                    difficulty: "easy",
                    img: "https://images.unsplash.com/photo-1564507592333-c60657eea023?auto=format&fit=crop&w=400&q=80"
                },
                {
                    q_en: "Which planet is known as the 'Red Planet'?",
                    q_hi: "किस ग्रह को 'लाल ग्रह' के रूप में जाना जाता है?",
                    options_en: ["Venus", "Mars", "Jupiter", "Saturn"],
                    options_hi: ["शुक्र", "मंगल", "बृहस्पति", "शनि"],
                    answer: 1,
                    hint_en: "It is the fourth planet from the Sun.",
                    hint_hi: "यह सूर्य से चौथा ग्रह है।",
                    explanation_en: "Mars is known as the Red Planet because of iron oxide on its surface.",
                    explanation_hi: "सतह पर आयरन ऑक्साइड के कारण मंगल को लाल ग्रह कहा जाता है।",
                    difficulty: "easy"
                },
                {
                    q_en: "Who wrote the Indian National Anthem?",
                    q_hi: "भारत का राष्ट्रगान किसने लिखा था?",
                    options_en: ["Bankim Chandra Chatterjee", "Rabindranath Tagore", "Sarojini Naidu", "Mahatma Gandhi"],
                    options_hi: ["बंकिम चंद्र चटर्जी", "रवींद्रनाथ टैगोर", "सरोजिनी नायडू", "महात्मा गांधी"],
                    answer: 1,
                    hint_en: "He was the first Asian to win a Nobel Prize.",
                    hint_hi: "वे नोबेल पुरस्कार जीतने वाले पहले एशियाई थे।",
                    explanation_en: "Rabindranath Tagore wrote 'Jana Gana Mana' in 1911.",
                    explanation_hi: "रवींद्रनाथ टैगोर ने 1911 में 'जन गण मन' लिखा था।",
                    difficulty: "medium"
                },
                {
                    q_en: "Which is the smallest country in the world?",
                    q_hi: "दुनिया का सबसे छोटा देश कौन सा है?",
                    options_en: ["Monaco", "Vatican City", "San Marino", "Liechtenstein"],
                    options_hi: ["मोनाको", "वेटिकन सिटी", "सैन मैरिनो", "लिकटेंस्टीन"],
                    answer: 1,
                    hint_en: "It is located within the city of Rome.",
                    hint_hi: "यह रोम शहर के भीतर स्थित है।",
                    explanation_en: "Vatican City is the smallest country by both area and population.",
                    explanation_hi: "क्षेत्रफल और जनसंख्या दोनों के मामले में वेटिकन सिटी सबसे छोटा देश है।",
                    difficulty: "medium"
                },
                {
                    q_en: "What is the capital of France?",
                    q_hi: "फ्रांस की राजधानी क्या है?",
                    options_en: ["Berlin", "London", "Madrid", "Paris"],
                    options_hi: ["बर्लिन", "लंदन", "मैड्रिड", "पेरिस"],
                    answer: 3,
                    hint_en: "Known as the City of Light.",
                    hint_hi: "प्रकाश के शहर के रूप में जाना जाता है।",
                    explanation_en: "Paris is the capital and most populous city of France.",
                    explanation_hi: "पेरिस फ्रांस की राजधानी और सबसे अधिक आबादी वाला शहर है।",
                    difficulty: "easy"
                },
                {
                    q_en: "Which is the longest river in the world?",
                    q_hi: "दुनिया की सबसे लंबी नदी कौन सी है?",
                    options_en: ["Amazon", "Nile", "Yangtze", "Mississippi"],
                    options_hi: ["अमेज़न", "नील", "यांग्त्ज़ी", "मिसिसिपी"],
                    answer: 1,
                    hint_en: "It flows through northeastern Africa.",
                    hint_hi: "यह उत्तर-पूर्वी अफ्रीका से होकर बहती है।",
                    explanation_en: "The Nile is traditionally considered the longest river in the world.",
                    explanation_hi: "नील नदी को पारंपरिक रूप से दुनिया की सबसे लंबी नदी माना जाता है।",
                    difficulty: "medium"
                },
                {
                    q_en: "Who invented the telephone?",
                    q_hi: "टेलीफोन का आविष्कार किसने किया था?",
                    options_en: ["Thomas Edison", "Nikola Tesla", "Alexander Graham Bell", "Albert Einstein"],
                    options_hi: ["थॉमस एडिसन", "निकोला टेस्ला", "अलेक्जेंडर ग्राहम बेल", "अल्बर्ट आइंस्टीन"],
                    answer: 2,
                    hint_en: "His last name rhymes with the sound a phone makes.",
                    hint_hi: "उनका उपनाम फोन की आवाज से मिलता-जुलता है।",
                    explanation_en: "Alexander Graham Bell is credited with patenting the first practical telephone.",
                    explanation_hi: "अलेक्जेंडर ग्राहम बेल को पहले व्यावहारिक टेलीफोन के पेटेंट का श्रेय दिया जाता है।",
                    difficulty: "easy"
                },
                {
                    q_en: "Which is the largest animal in the world?",
                    q_hi: "दुनिया का सबसे बड़ा जानवर कौन सा है?",
                    options_en: ["Elephant", "Blue Whale", "Giraffe", "Shark"],
                    options_hi: ["हाथी", "ब्लू व्हेल", "जिराफ", "शार्क"],
                    answer: 1,
                    hint_en: "It lives in the ocean.",
                    hint_hi: "यह समुद्र में रहता है।",
                    explanation_en: "The Blue Whale is the largest animal ever known to have lived on Earth.",
                    explanation_hi: "ब्लू व्हेल पृथ्वी पर रहने वाला अब तक का सबसे बड़ा ज्ञात जानवर है।",
                    difficulty: "easy"
                },
                {
                    q_en: "Who was the first person to step on the Moon?",
                    q_hi: "चंद्रमा पर कदम रखने वाले पहले व्यक्ति कौन थे?",
                    options_en: ["Yuri Gagarin", "Neil Armstrong", "Buzz Aldrin", "Rakesh Sharma"],
                    options_hi: ["यूरी गागरिन", "नील आर्मस्ट्रांग", "बज़ एल्ड्रिन", "राकेश शर्मा"],
                    answer: 1,
                    hint_en: "He was an American astronaut in 1969.",
                    hint_hi: "वे 1969 में एक अमेरिकी अंतरिक्ष यात्री थे।",
                    explanation_en: "Neil Armstrong became the first human to step on the moon on July 20, 1969.",
                    explanation_hi: "नील आर्मस्ट्रांग 20 जुलाई, 1969 को चंद्रमा पर कदम रखने वाले पहले मानव बने।",
                    difficulty: "medium"
                },
                {
                    q_en: "Which is the fastest land animal?",
                    q_hi: "सबसे तेज़ ज़मीनी जानवर कौन सा है?",
                    options_en: ["Lion", "Tiger", "Cheetah", "Leopard"],
                    options_hi: ["शेर", "बाघ", "चीता", "तेंदुआ"],
                    answer: 2,
                    hint_en: "It can reach speeds of up to 120 km/h.",
                    hint_hi: "यह 120 किमी/घंटा तक की गति तक पहुँच सकता है।",
                    explanation_en: "The Cheetah is the fastest land animal, capable of accelerating from 0 to 96 km/h in three seconds.",
                    explanation_hi: "चीता सबसे तेज़ ज़मीनी जानवर है, जो तीन सेकंड में 0 से 96 किमी/घंटा की रफ़्तार पकड़ने में सक्षम है।",
                    difficulty: "easy"
                },
                {
                    q_en: "Which gas do humans need to breathe to survive?",
                    q_hi: "जीवित रहने के लिए मनुष्यों को किस गैस में सांस लेने की आवश्यकता होती है?",
                    options_en: ["Nitrogen", "Carbon Dioxide", "Oxygen", "Helium"],
                    options_hi: ["नाइट्रोजन", "कार्बन डाइऑक्साइड", "ऑक्सीजन", "हीलियम"],
                    answer: 2,
                    hint_en: "It makes up about 21% of Earth's atmosphere.",
                    hint_hi: "यह पृथ्वी के वायुमंडल का लगभग 21% हिस्सा बनाता है।",
                    explanation_en: "Humans need oxygen for cellular respiration to produce energy.",
                    explanation_hi: "ऊर्जा उत्पन्न करने के लिए मनुष्यों को कोशिकीय श्वसन के लिए ऑक्सीजन की आवश्यकता होती है।",
                    difficulty: "easy"
                },
                {
                    q_en: "How many colors are there in a rainbow?",
                    q_hi: "इंद्रधनुष में कितने रंग होते हैं?",
                    options_en: ["5", "6", "7", "8"],
                    options_hi: ["5", "6", "7", "8"],
                    answer: 2,
                    hint_en: "Remember the acronym VIBGYOR.",
                    hint_hi: "VIBGYOR संक्षिप्त नाम याद रखें।",
                    explanation_en: "A rainbow consists of seven colors: Violet, Indigo, Blue, Green, Yellow, Orange, and Red.",
                    explanation_hi: "इंद्रधनुष में सात रंग होते हैं: बैंगनी, जामुनी, नीला, हरा, पीला, नारंगी और लाल।",
                    difficulty: "easy"
                },
                {
                    q_en: "Which is the largest country in the world by area?",
                    q_hi: "क्षेत्रफल के आधार पर दुनिया का सबसे बड़ा देश कौन सा है?",
                    options_en: ["China", "USA", "Canada", "Russia"],
                    options_hi: ["चीन", "यूएसए", "कनाडा", "रूस"],
                    answer: 3,
                    hint_en: "It spans across both Europe and Asia.",
                    hint_hi: "यह यूरोप और एशिया दोनों में फैला हुआ है।",
                    explanation_en: "Russia is the largest country by area, covering more than one-eighth of Earth's inhabited land area.",
                    explanation_hi: "रूस क्षेत्रफल के हिसाब से सबसे बड़ा देश है, जो पृथ्वी के बसे हुए भूमि क्षेत्र के आठवें हिस्से से अधिक को कवर करता है।",
                    difficulty: "medium"
                },
                {
                    q_en: "Who painted the Mona Lisa?",
                    q_hi: "मोना लिसा किसने चित्रित की थी?",
                    options_en: ["Vincent van Gogh", "Pablo Picasso", "Leonardo da Vinci", "Michelangelo"],
                    options_hi: ["विंसेंट वैन गॉग", "पाब्लो पिकासो", "लियोनार्डो द विंची", "माइकल एंजेलो"],
                    answer: 2,
                    hint_en: "He was a famous Italian polymath of the Renaissance.",
                    hint_hi: "वे पुनर्जागरण के एक प्रसिद्ध इतालवी बहुश्रुत थे।",
                    explanation_en: "Leonardo da Vinci painted the Mona Lisa in the early 16th century.",
                    explanation_hi: "लियोनार्डो द विंची ने 16वीं शताब्दी की शुरुआत में मोना लिसा को चित्रित किया था।",
                    difficulty: "medium"
                },
                {
                    q_en: "Which continent is known as the 'Dark Continent'?",
                    q_hi: "किस महाद्वीप को 'अंधेरा महाद्वीप' के रूप में जाना जाता है?",
                    options_en: ["Asia", "Africa", "South America", "Australia"],
                    options_hi: ["एशिया", "अफ्रीका", "दक्षिण अमेरिका", "ऑस्ट्रेलिया"],
                    answer: 1,
                    hint_en: "It is the second largest continent.",
                    hint_hi: "यह दूसरा सबसे बड़ा महाद्वीप है।",
                    explanation_en: "Africa was called the Dark Continent because it remained unexplored for a long time.",
                    explanation_hi: "अफ्रीका को अंधेरा महाद्वीप कहा जाता था क्योंकि यह लंबे समय तक अनछुआ रहा था।",
                    difficulty: "medium"
                },
                {
                    q_en: "Who is known as the Father of the Nation in India?",
                    q_hi: "भारत में राष्ट्रपिता के रूप में किसे जाना जाता है?",
                    options_en: ["Jawaharlal Nehru", "Subhash Chandra Bose", "Mahatma Gandhi", "Bhagat Singh"],
                    options_hi: ["जवाहरलाल नेहरू", "सुभाष चंद्र बोस", "महात्मा गांधी", "भगत सिंह"],
                    answer: 2,
                    hint_en: "His birthday is on October 2nd.",
                    hint_hi: "उनका जन्मदिन 2 अक्टूबर को होता है।",
                    explanation_en: "Mahatma Gandhi is called the Father of the Nation for his leadership in the independence movement.",
                    explanation_hi: "स्वतंत्रता आंदोलन में उनके नेतृत्व के लिए महात्मा गांधी को राष्ट्रपिता कहा जाता है।",
                    difficulty: "easy"
                },
                {
                    q_en: "Which is the smallest continent in the world?",
                    q_hi: "दुनिया का सबसे छोटा महाद्वीप कौन सा है?",
                    options_en: ["Europe", "Antarctica", "Australia", "South America"],
                    options_hi: ["यूरोप", "अंटार्कटिका", "ऑस्ट्रेलिया", "दक्षिण अमेरिका"],
                    answer: 2,
                    hint_en: "It is also known as the Island Continent.",
                    hint_hi: "इसे द्वीप महाद्वीप के रूप में भी जाना जाता है।",
                    explanation_en: "Australia is the smallest continent and also a country.",
                    explanation_hi: "ऑस्ट्रेलिया सबसे छोटा महाद्वीप है और एक देश भी है।",
                    difficulty: "easy"
                }
            ],
            2: [], 3: [], 4: [], 5: [], 6: []
        }
    },
    science: {
        title_en: "Science",
        title_hi: "विज्ञान",
        sections: {
            1: [
                {
                    q_en: "What is the chemical symbol for Water?",
                    q_hi: "पानी का रासायनिक सूत्र क्या है?",
                    options_en: ["O2", "CO2", "H2O", "NaCl"],
                    options_hi: ["O2", "CO2", "H2O", "NaCl"],
                    answer: 2,
                    hint_en: "Two hydrogen atoms and one oxygen atom.",
                    hint_hi: "दो हाइड्रोजन परमाणु और एक ऑक्सीजन परमाणु।",
                    explanation_en: "H2O stands for two Hydrogen atoms and one Oxygen atom.",
                    explanation_hi: "H2O का अर्थ है दो हाइड्रोजन परमाणु और एक ऑक्सीजन परमाणु।",
                    difficulty: "easy"
                },
                {
                    q_en: "Which gas do plants absorb from the atmosphere for photosynthesis?",
                    q_hi: "प्रकाश संश्लेषण के लिए पौधे वायुमंडल से कौन सी गैस अवशोषित करते हैं?",
                    options_en: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"],
                    options_hi: ["ऑक्सीजन", "कार्बन डाइऑक्साइड", "नाइट्रोजन", "हाइड्रोजन"],
                    answer: 1,
                    hint_en: "It is the gas humans breathe out.",
                    hint_hi: "यह वह गैस है जिसे मनुष्य बाहर छोड़ते हैं।",
                    explanation_en: "Plants use Carbon Dioxide and sunlight to produce food.",
                    explanation_hi: "पौधे भोजन बनाने के लिए कार्बन डाइऑक्साइड और सूर्य के प्रकाश का उपयोग करते हैं।",
                    difficulty: "easy"
                },
                {
                    q_en: "What is the power house of the cell?",
                    q_hi: "कोशिका का पावर हाउस किसे कहा जाता है?",
                    options_en: ["Nucleus", "Ribosome", "Mitochondria", "Cytoplasm"],
                    options_hi: ["नाभिक", "राइबोसोम", "माइटोकॉन्ड्रिया", "साइटोप्लाज्म"],
                    answer: 2,
                    hint_en: "It generates energy for the cell.",
                    hint_hi: "यह कोशिका के लिए ऊर्जा उत्पन्न करता है।",
                    explanation_en: "Mitochondria are responsible for creating ATP, the cell's energy currency.",
                    explanation_hi: "माइटोकॉन्ड्रिया एटीपी बनाने के लिए जिम्मेदार हैं, जो कोशिका की ऊर्जा मुद्रा है।",
                    difficulty: "medium"
                },
                {
                    q_en: "Which planet is closest to the Sun?",
                    q_hi: "सूर्य के सबसे निकट कौन सा ग्रह है?",
                    options_en: ["Venus", "Mars", "Mercury", "Earth"],
                    options_hi: ["शुक्र", "मंगल", "बुध", "पृथ्वी"],
                    answer: 2,
                    hint_en: "It's the smallest planet in the solar system.",
                    hint_hi: "यह सौरमंडल का सबसे छोटा ग्रह है।",
                    explanation_en: "Mercury is the closest planet to the Sun and has the shortest orbital period.",
                    explanation_hi: "बुध सूर्य के सबसे निकट का ग्रह है और इसकी कक्षीय अवधि सबसे कम है।",
                    difficulty: "easy"
                },
                {
                    q_en: "What is the hardest natural substance on Earth?",
                    q_hi: "पृथ्वी पर सबसे कठोर प्राकृतिक पदार्थ कौन सा है?",
                    options_en: ["Gold", "Iron", "Diamond", "Platinum"],
                    options_hi: ["सोना", "लोहा", "हीरा", "प्लैटिनम"],
                    answer: 2,
                    hint_en: "It is commonly used in jewelry.",
                    hint_hi: "इसका उपयोग आमतौर पर गहनों में किया जाता है।",
                    explanation_en: "Diamond is the hardest known natural material on Earth.",
                    explanation_hi: "हीरा पृथ्वी पर ज्ञात सबसे कठोर प्राकृतिक पदार्थ है।",
                    difficulty: "medium"
                },
                {
                    q_en: "Which part of the human body produces insulin?",
                    q_hi: "मानव शरीर का कौन सा हिस्सा इंसुलिन पैदा करता है?",
                    options_en: ["Liver", "Pancreas", "Kidney", "Stomach"],
                    options_hi: ["यकृत", "अग्न्याशय", "गुर्दा", "पेट"],
                    answer: 1,
                    hint_en: "Located behind the stomach.",
                    hint_hi: "पेट के पीछे स्थित है।",
                    explanation_en: "The pancreas produces insulin to regulate blood sugar levels.",
                    explanation_hi: "अग्न्याशय रक्त शर्करा के स्तर को नियंत्रित करने के लिए इंसुलिन का उत्पादन करता है।",
                    difficulty: "medium"
                },
                {
                    q_en: "What is the speed of light?",
                    q_hi: "प्रकाश की गति क्या है?",
                    options_en: ["300,000 km/s", "150,000 km/s", "1,000,000 km/s", "500,000 km/s"],
                    options_hi: ["300,000 km/s", "150,000 km/s", "1,000,000 km/s", "500,000 km/s"],
                    answer: 0,
                    hint_en: "It's approximately 3 * 10^8 meters per second.",
                    hint_hi: "यह लगभग 3 * 10^8 मीटर प्रति सेकंड है।",
                    explanation_en: "Light travels at approximately 299,792 kilometers per second in a vacuum.",
                    explanation_hi: "निर्वात में प्रकाश लगभग 299,792 किलोमीटर प्रति सेकंड की गति से चलता है।",
                    difficulty: "hard"
                },
                {
                    q_en: "Who proposed the Theory of Relativity?",
                    q_hi: "सापेक्षता का सिद्धांत किसने प्रस्तावित किया था?",
                    options_en: ["Isaac Newton", "Albert Einstein", "Stephen Hawking", "Galileo Galilei"],
                    options_hi: ["आईजैक न्यूटन", "अल्बर्ट आइंस्टीन", "स्टीफन हॉकिंग", "गैलीलियो गैलीली"],
                    answer: 1,
                    hint_en: "Famous for E=mc^2.",
                    hint_hi: "E=mc^2 के लिए प्रसिद्ध है।",
                    explanation_en: "Albert Einstein developed the special and general theories of relativity.",
                    explanation_hi: "अल्बर्ट आइंस्टीन ने सापेक्षता के विशेष और सामान्य सिद्धांतों को विकसित किया।",
                    difficulty: "medium"
                },
                {
                    q_en: "What is the boiling point of water at sea level?",
                    q_hi: "समुद्र तल पर पानी का क्वथनांक क्या है?",
                    options_en: ["90°C", "100°C", "110°C", "120°C"],
                    options_hi: ["90°C", "100°C", "110°C", "120°C"],
                    answer: 1,
                    hint_en: "It's exactly 100 on the Celsius scale.",
                    hint_hi: "सेल्सियस पैमाने पर यह ठीक 100 है।",
                    explanation_en: "At standard atmospheric pressure, water boils at 100°C.",
                    explanation_hi: "मानक वायुमंडलीय दबाव पर, पानी 100°C पर उबलता है।",
                    difficulty: "easy"
                },
                {
                    q_en: "Which element has the atomic number 1?",
                    q_hi: "किस तत्व की परमाणु संख्या 1 है?",
                    options_en: ["Helium", "Oxygen", "Hydrogen", "Carbon"],
                    options_hi: ["हीलियम", "ऑक्सीजन", "हाइड्रोजन", "कार्बन"],
                    answer: 2,
                    hint_en: "It is the most abundant element in the universe.",
                    hint_hi: "यह ब्रह्मांड में सबसे प्रचुर मात्रा में पाया जाने वाला तत्व है।",
                    explanation_en: "Hydrogen is the first element on the periodic table with one proton.",
                    explanation_hi: "हाइड्रोजन आवर्त सारणी का पहला तत्व है जिसमें एक प्रोटॉन होता है।",
                    difficulty: "medium"
                },
                {
                    q_en: "Which organ in the human body pumps blood?",
                    q_hi: "मानव शरीर का कौन सा अंग रक्त पंप करता है?",
                    options_en: ["Lungs", "Brain", "Heart", "Kidney"],
                    options_hi: ["फेफड़े", "मस्तिष्क", "हृदय", "गुर्दा"],
                    answer: 2,
                    hint_en: "It beats about 100,000 times a day.",
                    hint_hi: "यह दिन में लगभग 100,000 बार धड़कता है।",
                    explanation_en: "The heart is a muscular organ that pumps blood throughout the body.",
                    explanation_hi: "हृदय एक पेशीय अंग है जो पूरे शरीर में रक्त पंप करता है।",
                    difficulty: "easy"
                },
                {
                    q_en: "How many bones are there in an adult human body?",
                    q_hi: "एक वयस्क मानव शरीर में कितनी हड्डियाँ होती हैं?",
                    options_en: ["106", "206", "306", "406"],
                    options_hi: ["106", "206", "306", "406"],
                    answer: 1,
                    hint_en: "It's more than 200.",
                    hint_hi: "यह 200 से अधिक है।",
                    explanation_en: "An adult human has 206 bones, while infants are born with around 270.",
                    explanation_hi: "एक वयस्क मनुष्य में 206 हड्डियाँ होती हैं, जबकि शिशु लगभग 270 हड्डियों के साथ पैदा होते हैं।",
                    difficulty: "medium"
                },
                {
                    q_en: "What is the nearest star to Earth?",
                    q_hi: "पृथ्वी का निकटतम तारा कौन सा है?",
                    options_en: ["Sirius", "Proxima Centauri", "Sun", "North Star"],
                    options_hi: ["सीरियस", "प्रॉक्सिमा सेंटॉरी", "सूर्य", "ध्रुव तारा"],
                    answer: 2,
                    hint_en: "It provides light and heat during the day.",
                    hint_hi: "यह दिन के दौरान प्रकाश और गर्मी प्रदान करता है।",
                    explanation_en: "The Sun is the closest star to Earth and the center of our solar system.",
                    explanation_hi: "सूर्य पृथ्वी का निकटतम तारा है और हमारे सौर मंडल का केंद्र है।",
                    difficulty: "easy"
                },
                {
                    q_en: "What is the chemical symbol for Gold?",
                    q_hi: "सोने का रासायनिक सूत्र क्या है?",
                    options_en: ["Gd", "Go", "Ag", "Au"],
                    options_hi: ["Gd", "Go", "Ag", "Au"],
                    answer: 3,
                    hint_en: "It comes from the Latin word 'Aurum'.",
                    hint_hi: "यह लैटिन शब्द 'Aurum' से आया है।",
                    explanation_en: "Au is the chemical symbol for Gold on the periodic table.",
                    explanation_hi: "आवर्त सारणी पर सोने का रासायनिक सूत्र Au है।",
                    difficulty: "medium"
                },
                {
                    q_en: "Which planet has the most rings?",
                    q_hi: "किस ग्रह में सबसे अधिक छल्ले हैं?",
                    options_en: ["Jupiter", "Saturn", "Uranus", "Neptune"],
                    options_hi: ["बृहस्पति", "शनि", "अरुण", "वरुण"],
                    answer: 1,
                    hint_en: "It is the second-largest planet in the solar system.",
                    hint_hi: "यह सौरमंडल का दूसरा सबसे बड़ा ग्रह है।",
                    explanation_en: "Saturn has the most extensive ring system of any planet.",
                    explanation_hi: "शनि के पास किसी भी ग्रह का सबसे व्यापक वलय तंत्र है।",
                    difficulty: "easy"
                },
                {
                    q_en: "Which vitamin is obtained from sunlight?",
                    q_hi: "सूर्य के प्रकाश से कौन सा विटामिन प्राप्त होता है?",
                    options_en: ["Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"],
                    options_hi: ["विटामिन ए", "विटामिन बी", "विटामिन सी", "विटामिन डी"],
                    answer: 3,
                    hint_en: "It is essential for bone health.",
                    hint_hi: "यह हड्डियों के स्वास्थ्य के लिए आवश्यक है।",
                    explanation_en: "Your body produces vitamin D when your skin is exposed to sunlight.",
                    explanation_hi: "जब आपकी त्वचा सूर्य के प्रकाश के संपर्क में आती है तो आपका शरीर विटामिन डी बनाता है।",
                    difficulty: "easy"
                },
                {
                    q_en: "What is the study of living things called?",
                    q_hi: "जीवित चीजों के अध्ययन को क्या कहा जाता है?",
                    options_en: ["Physics", "Chemistry", "Biology", "Geology"],
                    options_hi: ["भौतिक विज्ञान", "रसायन विज्ञान", "जीव विज्ञान", "भूविज्ञान"],
                    answer: 2,
                    hint_en: "It comes from the Greek words for 'life' and 'study'.",
                    hint_hi: "यह 'जीवन' और 'अध्ययन' के लिए ग्रीक शब्दों से आया है।",
                    explanation_en: "Biology is the natural science that studies life and living organisms.",
                    explanation_hi: "जीव विज्ञान वह प्राकृतिक विज्ञान है जो जीवन और जीवित जीवों का अध्ययन करता है।",
                    difficulty: "easy"
                },
                {
                    q_en: "Which instrument is used to measure temperature?",
                    q_hi: "तापमान मापने के लिए किस उपकरण का उपयोग किया जाता है?",
                    options_en: ["Barometer", "Thermometer", "Hygrometer", "Speedometer"],
                    options_hi: ["बैरोमीटर", "थर्मामीटर", "हाइग्रोमीटर", "स्पीडोमीटर"],
                    answer: 1,
                    hint_en: "It often contains mercury or alcohol.",
                    hint_hi: "इसमें अक्सर पारा या अल्कोहल होता है।",
                    explanation_en: "A thermometer is a device that measures temperature or a temperature gradient.",
                    explanation_hi: "थर्मामीटर एक ऐसा उपकरण है जो तापमान या तापमान प्रवणता को मापता है।",
                    difficulty: "easy"
                },
                {
                    q_en: "What is the main gas found in the air we breathe?",
                    q_hi: "हम जिस हवा में सांस लेते हैं उसमें पाई जाने वाली मुख्य गैस कौन सी है?",
                    options_en: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Argon"],
                    options_hi: ["ऑक्सीजन", "कार्बन डाइऑक्साइड", "नाइट्रोजन", "आर्गन"],
                    answer: 2,
                    hint_en: "It makes up about 78% of the atmosphere.",
                    hint_hi: "यह वायुमंडल का लगभग 78% हिस्सा बनाता है।",
                    explanation_en: "Nitrogen is the most abundant gas in Earth's atmosphere.",
                    explanation_hi: "नाइट्रोजन पृथ्वी के वायुमंडल में सबसे प्रचुर मात्रा में पाई जाने वाली गैस है।",
                    difficulty: "medium"
                },
                {
                    q_en: "Who discovered gravity?",
                    q_hi: "गुरुत्वाकर्षण की खोज किसने की थी?",
                    options_en: ["Albert Einstein", "Isaac Newton", "Galileo Galilei", "Nikola Tesla"],
                    options_hi: ["अल्बर्ट आइंस्टीन", "आईजैक न्यूटन", "गैलीलियो गैलीली", "निकोला टेस्ला"],
                    answer: 1,
                    hint_en: "An apple supposedly fell on his head.",
                    hint_hi: "माना जाता है कि एक सेब उनके सिर पर गिरा था।",
                    explanation_en: "Sir Isaac Newton formulated the laws of motion and universal gravitation.",
                    explanation_hi: "सर आइजैक न्यूटन ने गति के नियमों और सार्वभौमिक गुरुत्वाकर्षण को प्रतिपादित किया।",
                    difficulty: "medium"
                }
            ],
            2: [], 3: [], 4: [], 5: [], 6: []
        }
    },
    history: {
        title_en: "History",
        title_hi: "इतिहास",
        sections: {
            1: [
                {
                    q_en: "Who was the first President of India?",
                    q_hi: "भारत के पहले राष्ट्रपति कौन थे?",
                    options_en: ["Dr. Rajendra Prasad", "Dr. S. Radhakrishnan", "Zakir Husain", "V.V. Giri"],
                    options_hi: ["डॉ. राजेंद्र प्रसाद", "डॉ. एस. राधाकृष्णन", "ज़ाकिर हुसैन", "वी.वी. गिरी"],
                    answer: 0,
                    hint_en: "He was born in Bihar.",
                    hint_hi: "उनका जन्म बिहार में हुआ था।",
                    explanation_en: "Dr. Rajendra Prasad was the first President of India from 1950 to 1962.",
                    explanation_hi: "डॉ. राजेंद्र प्रसाद 1950 से 1962 तक भारत के पहले राष्ट्रपति थे।",
                    difficulty: "medium"
                },
                {
                    q_en: "In which year did the First World War begin?",
                    q_hi: "प्रथम विश्व युद्ध किस वर्ष शुरू हुआ था?",
                    options_en: ["1912", "1914", "1918", "1939"],
                    options_hi: ["1912", "1914", "1918", "1939"],
                    answer: 1,
                    hint_en: "It started in the early 20th century.",
                    hint_hi: "यह 20वीं सदी की शुरुआत में शुरू हुआ था।",
                    explanation_en: "World War I lasted from 1914 to 1918.",
                    explanation_hi: "प्रथम विश्व युद्ध 1914 से 1918 तक चला था।",
                    difficulty: "medium"
                },
                {
                    q_en: "Who was the founder of the Mughal Empire in India?",
                    q_hi: "भारत में मुगल साम्राज्य का संस्थापक कौन था?",
                    options_en: ["Akbar", "Humayun", "Babur", "Shah Jahan"],
                    options_hi: ["अकबर", "हुमायूँ", "बाबर", "शाहजहाँ"],
                    answer: 2,
                    hint_en: "He won the First Battle of Panipat.",
                    hint_hi: "उन्होंने पानीपत की पहली लड़ाई जीती थी।",
                    explanation_en: "Babur founded the Mughal Empire after defeating Ibrahim Lodi in 1526.",
                    explanation_hi: "बाबर ने 1526 में इब्राहिम लोदी को हराकर मुगल साम्राज्य की स्थापना की थी।",
                    difficulty: "medium"
                },
                {
                    q_en: "Which Indian freedom fighter is known as 'Netaji'?",
                    q_hi: "किस भारतीय स्वतंत्रता सेनानी को 'नेताजी' के नाम से जाना जाता है?",
                    options_en: ["Bhagat Singh", "Subhash Chandra Bose", "Lala Lajpat Rai", "Chandra Shekhar Azad"],
                    options_hi: ["भगत सिंह", "सुभाष चंद्र बोस", "लाला लाजपत राय", "चंद्रशेखर आजाद"],
                    answer: 1,
                    hint_en: "He formed the Indian National Army (INA).",
                    hint_hi: "उन्होंने भारतीय राष्ट्रीय सेना (INA) का गठन किया था।",
                    explanation_en: "Subhash Chandra Bose was given the title Netaji by Indian soldiers in Germany.",
                    explanation_hi: "सुभाष चंद्र बोस को जर्मनी में भारतीय सैनिकों द्वारा नेताजी की उपाधि दी गई थी।",
                    difficulty: "easy"
                },
                {
                    q_en: "In which year did India get independence from British rule?",
                    q_hi: "भारत को ब्रिटिश शासन से स्वतंत्रता किस वर्ष मिली?",
                    options_en: ["1942", "1945", "1947", "1950"],
                    options_hi: ["1942", "1945", "1947", "1950"],
                    answer: 2,
                    hint_en: "It's celebrated every August 15th.",
                    hint_hi: "यह हर 15 अगस्त को मनाया जाता है।",
                    explanation_en: "India became independent on August 15, 1947.",
                    explanation_hi: "भारत 15 अगस्त 1947 को स्वतंत्र हुआ।",
                    difficulty: "easy"
                },
                {
                    q_en: "Who was the first woman Prime Minister of India?",
                    q_hi: "भारत की पहली महिला प्रधानमंत्री कौन थीं?",
                    options_en: ["Pratibha Patil", "Indira Gandhi", "Sushma Swaraj", "Sarojini Naidu"],
                    options_hi: ["प्रतिभा पाटिल", "इंदिरा गांधी", "सुषमा स्वराज", "सरोजिनी नायडू"],
                    answer: 1,
                    hint_en: "She was the daughter of Jawaharlal Nehru.",
                    hint_hi: "वह जवाहरलाल नेहरू की बेटी थीं।",
                    explanation_en: "Indira Gandhi served as Prime Minister from 1966 to 1977 and again from 1980 to 1984.",
                    explanation_hi: "इंदिरा गांधी ने 1966 से 1977 तक और फिर 1980 से 1984 तक प्रधानमंत्री के रूप में कार्य किया।",
                    difficulty: "easy"
                },
                {
                    q_en: "The Quit India Movement was started in which year?",
                    q_hi: "भारत छोड़ो आंदोलन किस वर्ष शुरू किया गया था?",
                    options_en: ["1930", "1942", "1919", "1947"],
                    options_hi: ["1930", "1942", "1919", "1947"],
                    answer: 1,
                    hint_en: "Launched by Mahatma Gandhi during WWII.",
                    hint_hi: "द्वितीय विश्व युद्ध के दौरान महात्मा गांधी द्वारा शुरू किया गया।",
                    explanation_en: "The Quit India Movement was launched on August 8, 1942.",
                    explanation_hi: "भारत छोड़ो आंदोलन 8 अगस्त 1942 को शुरू किया गया था।",
                    difficulty: "medium"
                },
                {
                    q_en: "Who was the first Governor-General of independent India?",
                    q_hi: "स्वतंत्र भारत के पहले गवर्नर-जनरल कौन थे?",
                    options_en: ["Lord Mountbatten", "C. Rajagopalachari", "Jawaharlal Nehru", "Dr. Rajendra Prasad"],
                    options_hi: ["लॉर्ड माउंटबेटन", "सी. राजगोपालाचारी", "जवाहरलाल नेहरू", "डॉ. राजेंद्र प्रसाद"],
                    answer: 0,
                    hint_en: "He was a British statesman.",
                    hint_hi: "वे एक ब्रिटिश राजनेता थे।",
                    explanation_en: "Lord Mountbatten was the last Viceroy and first Governor-General of independent India.",
                    explanation_hi: "लॉर्ड माउंटबेटन अंतिम वायसराय और स्वतंत्र भारत के पहले गवर्नर-जनरल थे।",
                    difficulty: "hard"
                },
                {
                    q_en: "Which emperor built the Sanchi Stupa?",
                    q_hi: "सांची स्तूप का निर्माण किस सम्राट ने करवाया था?",
                    options_en: ["Chandragupta Maurya", "Ashoka", "Kanishka", "Samudragupta"],
                    options_hi: ["चंद्रगुप्त मौर्य", "अशोक", "कनिष्क", "समुद्रगुप्त"],
                    answer: 1,
                    hint_en: "Known for spreading Buddhism.",
                    hint_hi: "बौद्ध धर्म के प्रसार के लिए जाने जाते हैं।",
                    explanation_en: "Emperor Ashoka the Great commissioned the Sanchi Stupa in the 3rd century BCE.",
                    explanation_hi: "सम्राट अशोक महान ने तीसरी शताब्दी ईसा पूर्व में सांची स्तूप का निर्माण करवाया था।",
                    difficulty: "medium"
                },
                {
                    q_en: "Who was the teacher of Alexander the Great?",
                    q_hi: "सिकंदर महान का शिक्षक कौन था?",
                    options_en: ["Socrates", "Plato", "Aristotle", "Pythagoras"],
                    options_hi: ["सुकरात", "प्लेटो", "अरस्तू", "पाइथागोरस"],
                    answer: 2,
                    hint_en: "A famous Greek philosopher.",
                    hint_hi: "एक प्रसिद्ध यूनानी दार्शनिक।",
                    explanation_en: "Aristotle was hired by Philip II of Macedon to tutor Alexander.",
                    explanation_hi: "मैसेडोन के फिलिप द्वितीय ने सिकंदर को ट्यूशन देने के लिए अरस्तू को काम पर रखा था।",
                    difficulty: "hard"
                },
                {
                    q_en: "Who was the first Prime Minister of India?",
                    q_hi: "भारत के पहले प्रधानमंत्री कौन थे?",
                    options_en: ["Mahatma Gandhi", "Jawaharlal Nehru", "Sardar Patel", "Lal Bahadur Shastri"],
                    options_hi: ["महात्मा गांधी", "जवाहरलाल नेहरू", "सरदार पटेल", "लाल बहादुर शास्त्री"],
                    answer: 1,
                    hint_en: "He is also known as 'Chacha Nehru'.",
                    hint_hi: "उन्हें 'चाचा नेहरू' के नाम से भी जाना जाता है।",
                    explanation_en: "Jawaharlal Nehru was the first Prime Minister of independent India from 1947 to 1964.",
                    explanation_hi: "जवाहरलाल नेहरू 1947 से 1964 तक स्वतंत्र भारत के पहले प्रधानमंत्री थे।",
                    difficulty: "easy"
                },
                {
                    q_en: "The French Revolution began in which year?",
                    q_hi: "फ्रांसीसी क्रांति किस वर्ष शुरू हुई थी?",
                    options_en: ["1776", "1789", "1799", "1804"],
                    options_hi: ["1776", "1789", "1799", "1804"],
                    answer: 1,
                    hint_en: "It's the same year the US Constitution was ratified.",
                    hint_hi: "यह वही वर्ष है जब अमेरिकी संविधान की पुष्टि की गई थी।",
                    explanation_en: "The French Revolution began in 1789 and led to the end of the monarchy in France.",
                    explanation_hi: "फ्रांसीसी क्रांति 1789 में शुरू हुई और फ्रांस में राजशाही के अंत का कारण बनी।",
                    difficulty: "hard"
                },
                {
                    q_en: "Who was the leader of the Nazi Party in Germany?",
                    q_hi: "जर्मनी में नाजी पार्टी का नेता कौन था?",
                    options_en: ["Benito Mussolini", "Adolf Hitler", "Joseph Stalin", "Winston Churchill"],
                    options_hi: ["बेनिटो मुसोलिनी", "एडोल्फ हिटलर", "जोसेफ स्टालिन", "विंस्टन चर्चिल"],
                    answer: 1,
                    hint_en: "He wrote 'Mein Kampf'.",
                    hint_hi: "उन्होंने 'मीन काम्फ' लिखी थी।",
                    explanation_en: "Adolf Hitler was the leader of the Nazi Party and Chancellor of Germany from 1933 to 1945.",
                    explanation_hi: "एडोल्फ हिटलर नाजी पार्टी के नेता और 1933 से 1945 तक जर्मनी के चांसलर थे।",
                    difficulty: "medium"
                },
                {
                    q_en: "Which city was the first to be attacked by an atomic bomb?",
                    q_hi: "परमाणु बम से हमला होने वाला पहला शहर कौन सा था?",
                    options_en: ["Tokyo", "Hiroshima", "Nagasaki", "Berlin"],
                    options_hi: ["टोक्यो", "हिरोशिमा", "नागासाकी", "बर्लिन"],
                    answer: 1,
                    hint_en: "The bomb was named 'Little Boy'.",
                    hint_hi: "बम का नाम 'लिटिल बॉय' था।",
                    explanation_en: "Hiroshima was bombed by the United States on August 6, 1945.",
                    explanation_hi: "6 अगस्त, 1945 को संयुक्त राज्य अमेरिका द्वारा हिरोशिमा पर बमबारी की गई थी।",
                    difficulty: "medium"
                },
                {
                    q_en: "Who was the first woman to fly solo across the Atlantic?",
                    q_hi: "अटलांटिक के पार अकेले उड़ान भरने वाली पहली महिला कौन थीं?",
                    options_en: ["Amelia Earhart", "Bessie Coleman", "Amy Johnson", "Valentina Tereshkova"],
                    options_hi: ["अमेलिया इयरहार्ट", "बेसी कोलमैन", "एमी जॉनसन", "वेलेंटीना टेरेशकोवा"],
                    answer: 0,
                    hint_en: "She disappeared mysteriously during a flight.",
                    hint_hi: "एक उड़ान के दौरान वह रहस्यमय तरीके से गायब हो गई थी।",
                    explanation_en: "Amelia Earhart was the first female aviator to fly solo across the Atlantic Ocean.",
                    explanation_hi: "अमेलिया इयरहार्ट अटलांटिक महासागर के पार अकेले उड़ान भरने वाली पहली महिला एविएटर थीं।",
                    difficulty: "hard"
                },
                {
                    q_en: "The Great Wall of China was built to protect against which invaders?",
                    q_hi: "चीन की महान दीवार किस हमलावरों से रक्षा के लिए बनाई गई थी?",
                    options_en: ["Romans", "Mongols", "Greeks", "Persians"],
                    options_hi: ["रोमन", "मंगोल", "यूनानी", "फारसी"],
                    answer: 1,
                    hint_en: "Nomadic tribes from the north.",
                    hint_hi: "उत्तर से खानाबदोश जनजातियाँ।",
                    explanation_en: "The wall was built across the historical northern borders of China to protect against nomadic groups.",
                    explanation_hi: "खानाबदोश समूहों से रक्षा के लिए चीन की ऐतिहासिक उत्तरी सीमाओं पर दीवार बनाई गई थी।",
                    difficulty: "medium"
                },
                {
                    q_en: "Who was the third President of the United States?",
                    q_hi: "संयुक्त राज्य अमेरिका के तीसरे राष्ट्रपति कौन थे?",
                    options_en: ["George Washington", "John Adams", "Thomas Jefferson", "James Madison"],
                    options_hi: ["जॉर्ज वाशिंगटन", "जॉन एडम्स", "थॉमस जेफरसन", "जेम्स मेडिसन"],
                    answer: 2,
                    hint_en: "He was the principal author of the Declaration of Independence.",
                    hint_hi: "वे स्वतंत्रता की घोषणा के मुख्य लेखक थे।",
                    explanation_en: "Thomas Jefferson served as the third US president from 1801 to 1809.",
                    explanation_hi: "थॉमस जेफरसन ने 1801 से 1809 तक तीसरे अमेरिकी राष्ट्रपति के रूप में कार्य किया।",
                    difficulty: "hard"
                },
                {
                    q_en: "In which year did the Titanic sink?",
                    q_hi: "टाइटेनिक किस वर्ष डूबा था?",
                    options_en: ["1905", "1912", "1918", "1923"],
                    options_hi: ["1905", "1912", "1918", "1923"],
                    answer: 1,
                    hint_en: "It was on its maiden voyage.",
                    hint_hi: "यह अपनी पहली यात्रा पर था।",
                    explanation_en: "The RMS Titanic sank in the North Atlantic Ocean on April 15, 1912.",
                    explanation_hi: "आरएमएस टाइटेनिक 15 अप्रैल, 1912 को उत्तरी अटलांटिक महासागर में डूब गया था।",
                    difficulty: "medium"
                },
                {
                    q_en: "Who was the Egyptian queen famous for her beauty?",
                    q_hi: "अपनी सुंदरता के लिए प्रसिद्ध मिस्र की रानी कौन थीं?",
                    options_en: ["Nefertiti", "Cleopatra", "Hatshepsut", "Isis"],
                    options_hi: ["नेफ़र्टिटी", "क्लियोपेट्रा", "हत्शेपसट", "आइसिस"],
                    answer: 1,
                    hint_en: "She had relationships with Julius Caesar and Mark Antony.",
                    hint_hi: "उनके जूलियस सीज़र और मार्क एंटनी के साथ संबंध थे।",
                    explanation_en: "Cleopatra VII was the last active ruler of the Ptolemaic Kingdom of Egypt.",
                    explanation_hi: "क्लियोपेट्रा VII मिस्र के टॉलेमिक साम्राज्य की अंतिम सक्रिय शासक थीं।",
                    difficulty: "medium"
                },
                {
                    q_en: "The Magna Carta was signed in which year?",
                    q_hi: "मैग्ना कार्टा पर किस वर्ष हस्ताक्षर किए गए थे?",
                    options_en: ["1066", "1215", "1492", "1588"],
                    options_hi: ["1066", "1215", "1492", "1588"],
                    answer: 1,
                    hint_en: "It happened in the 13th century.",
                    hint_hi: "यह 13वीं शताब्दी में हुआ था।",
                    explanation_en: "The Magna Carta was issued in June 1215 and was the first document to put into writing the principle that the king and his government were not above the law.",
                    explanation_hi: "मैग्ना कार्टा जून 1215 में जारी किया गया था और यह लिखित रूप में इस सिद्धांत को रखने वाला पहला दस्तावेज़ था कि राजा और उसकी सरकार कानून से ऊपर नहीं थे।",
                    difficulty: "hard"
                }
            ],
            2: [], 3: [], 4: [], 5: [], 6: []
        }
    },
    geography: {
        title_en: "Geography",
        title_hi: "भूगोल",
        sections: {
            1: [
                {
                    q_en: "Which is the largest desert in the world?",
                    q_hi: "दुनिया का सबसे बड़ा रेगिस्तान कौन सा है?",
                    options_en: ["Sahara", "Gobi", "Kalahari", "Antarctic Desert"],
                    options_hi: ["सहारा", "गोबी", "कालाहारी", "अंटार्टिक रेगिस्तान"],
                    answer: 3,
                    hint_en: "It's not a hot desert.",
                    hint_hi: "यह गर्म रेगिस्तान नहीं है।",
                    explanation_en: "Antarctica is technically a desert because it receives very little precipitation.",
                    explanation_hi: "अंटार्कटिका तकनीकी रूप से एक रेगिस्तान है क्योंकि वहां बहुत कम वर्षा होती है।",
                    difficulty: "hard"
                },
                {
                    q_en: "Mount Everest is located in which mountain range?",
                    q_hi: "माउंट एवरेस्ट किस पर्वत श्रृंखला में स्थित है?",
                    options_en: ["Andes", "Alps", "Himalayas", "Rockies"],
                    options_hi: ["एंडिस", "आल्प्स", "हिमालय", "रॉकीज"],
                    answer: 2,
                    hint_en: "It is the highest mountain range in the world.",
                    hint_hi: "यह दुनिया की सबसे ऊंची पर्वत श्रृंखला है।",
                    explanation_en: "The Himalayas contain the world's highest peaks, including Everest.",
                    explanation_hi: "हिमालय में एवरेस्ट सहित दुनिया की सबसे ऊंची चोटियाँ हैं।",
                    difficulty: "easy"
                },
                {
                    q_en: "Which is the largest ocean in the world?",
                    q_hi: "दुनिया का सबसे बड़ा महासागर कौन सा है?",
                    options_en: ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Pacific Ocean"],
                    options_hi: ["अटलांटिक महासागर", "हिंद महासागर", "आर्कटिक महासागर", "प्रशांत महासागर"],
                    answer: 3,
                    hint_en: "It covers more than one-third of the Earth's surface.",
                    hint_hi: "यह पृथ्वी की सतह के एक तिहाई से अधिक हिस्से को कवर करता है।",
                    explanation_en: "The Pacific Ocean is the largest and deepest of Earth's oceanic divisions.",
                    explanation_hi: "प्रशांत महासागर पृथ्वी के महासागरीय विभाजनों में सबसे बड़ा और गहरा है।",
                    difficulty: "easy"
                },
                {
                    q_en: "Which country is known as the 'Land of the Rising Sun'?",
                    q_hi: "किस देश को 'उगते सूरज की भूमि' के रूप में जाना जाता है?",
                    options_en: ["China", "Japan", "South Korea", "Thailand"],
                    options_hi: ["चीन", "जापान", "दक्षिण कोरिया", "थाईलैंड"],
                    answer: 1,
                    hint_en: "It's an island nation in East Asia.",
                    hint_hi: "यह पूर्वी एशिया का एक द्वीप देश है।",
                    explanation_en: "Japan is called Nihon in Japanese, which literally means 'sun origin'.",
                    explanation_hi: "जापान को जापानी में निहोन कहा जाता है, जिसका शाब्दिक अर्थ है 'सूर्य की उत्पत्ति' ।",
                    difficulty: "easy"
                },
                {
                    q_en: "Which is the largest continent in the world?",
                    q_hi: "दुनिया का सबसे बड़ा महाद्वीप कौन सा है?",
                    options_en: ["Africa", "North America", "Asia", "Europe"],
                    options_hi: ["अफ्रीका", "उत्तरी अमेरिका", "एशिया", "यूरोप"],
                    answer: 2,
                    hint_en: "It includes countries like India and China.",
                    hint_hi: "इसमें भारत और चीन जैसे देश शामिल हैं।",
                    explanation_en: "Asia is the largest continent in both area and population.",
                    explanation_hi: "एशिया क्षेत्रफल और जनसंख्या दोनों में सबसे बड़ा महाद्वीप है।",
                    difficulty: "easy"
                },
                {
                    q_en: "Which river is known as the 'Life Line of India'?",
                    q_hi: "किस नदी को 'भारत की जीवन रेखा' के रूप में जाना जाता है?",
                    options_en: ["Yamuna", "Ganga", "Brahmaputra", "Godavari"],
                    options_hi: ["यमुना", "गंगा", "ब्रह्मपुत्र", "गोदावरी"],
                    answer: 1,
                    hint_en: "It is the most sacred river for Hindus.",
                    hint_hi: "यह हिंदुओं के लिए सबसे पवित्र नदी है।",
                    explanation_en: "The Ganges (Ganga) is the longest river in India and is considered holy.",
                    explanation_hi: "गंगा भारत की सबसे लंबी नदी है और इसे पवित्र माना जाता है।",
                    difficulty: "easy"
                },
                {
                    q_en: "The equator passes through which of these continents?",
                    q_hi: "भूमध्य रेखा इनमें से किस महाद्वीप से होकर गुजरती है?",
                    options_en: ["Europe", "North America", "Africa", "Antarctica"],
                    options_hi: ["यूरोप", "उत्तरी अमेरिका", "अफ्रीका", "अंटार्कटिका"],
                    answer: 2,
                    hint_en: "This continent is home to the Nile river.",
                    hint_hi: "यह महाद्वीप नील नदी का घर है।",
                    explanation_en: "The Equator passes through Africa, South America, and Asia.",
                    explanation_hi: "भूमध्य रेखा अफ्रीका, दक्षिण अमेरिका और एशिया से होकर गुजरती है।",
                    difficulty: "medium"
                },
                {
                    q_en: "Which city is known as the 'Pink City' of India?",
                    q_hi: "भारत के किस शहर को 'गुलाबी शहर' के रूप में जाना जाता है?",
                    options_en: ["Jodhpur", "Udaipur", "Jaipur", "Bikaner"],
                    options_hi: ["जोधपुर", "उदयपुर", "जयपुर", "बीकानेर"],
                    answer: 2,
                    hint_en: "It's the capital of Rajasthan.",
                    hint_hi: "यह राजस्थान की राजधानी है।",
                    explanation_en: "Jaipur was painted pink to welcome Prince Albert in 1876.",
                    explanation_hi: "1876 में प्रिंस अल्बर्ट के स्वागत के लिए जयपुर को गुलाबी रंग से रंगा गया था।",
                    difficulty: "easy"
                },
                {
                    q_en: "Which is the highest waterfall in the world?",
                    q_hi: "दुनिया का सबसे ऊंचा जलप्रपात कौन सा है?",
                    options_en: ["Niagara Falls", "Victoria Falls", "Angel Falls", "Iguazu Falls"],
                    options_hi: ["नियाग्रा जलप्रपात", "विक्टोरिया जलप्रपात", "एंजेल जलप्रपात", "इगुआज़ु जलप्रपात"],
                    answer: 2,
                    hint_en: "It is located in Venezuela.",
                    hint_hi: "यह वेनेजुएला में स्थित है।",
                    explanation_en: "Angel Falls in Venezuela is the world's highest uninterrupted waterfall.",
                    explanation_hi: "वेनेजुएला में एंजेल जलप्रपात दुनिया का सबसे ऊंचा निर्बाध जलप्रपात है।",
                    difficulty: "medium"
                },
                {
                    q_en: "Which country has the most volcanoes?",
                    q_hi: "किस देश में सबसे अधिक ज्वालामुखी हैं?",
                    options_en: ["Japan", "Iceland", "Indonesia", "USA"],
                    options_hi: ["जापान", "आइसलैंड", "इंडोनेशिया", "यूएसए"],
                    answer: 2,
                    hint_en: "It is an archipelago in Southeast Asia.",
                    hint_hi: "यह दक्षिण पूर्व एशिया में एक द्वीपसमूह है।",
                    explanation_en: "Indonesia has the highest number of active volcanoes in the world.",
                    explanation_hi: "इंडोनेशिया में दुनिया में सबसे अधिक सक्रिय ज्वालामुखी हैं।",
                    difficulty: "hard"
                },
                {
                    q_en: "Which is the largest state in India by area?",
                    q_hi: "क्षेत्रफल के आधार पर भारत का सबसे बड़ा राज्य कौन सा है?",
                    options_en: ["Uttar Pradesh", "Maharashtra", "Rajasthan", "Madhya Pradesh"],
                    options_hi: ["उत्तर प्रदेश", "महाराष्ट्र", "राजस्थान", "मध्य प्रदेश"],
                    answer: 2,
                    hint_en: "It is mostly covered by the Thar Desert.",
                    hint_hi: "यह मुख्य रूप से थार मरुस्थल से ढका हुआ है।",
                    explanation_en: "Rajasthan is the largest Indian state by area, located in the northwestern part of the country.",
                    explanation_hi: "राजस्थान क्षेत्रफल के हिसाब से भारत का सबसे बड़ा राज्य है, जो देश के उत्तर-पश्चिमी भाग में स्थित है।",
                    difficulty: "easy"
                },
                {
                    q_en: "Which river flows through London?",
                    q_hi: "लंदन से होकर कौन सी नदी बहती है?",
                    options_en: ["Seine", "Thames", "Danube", "Rhine"],
                    options_hi: ["सीन", "टेम्स", "डेन्यूब", "राइन"],
                    answer: 1,
                    hint_en: "It's a very famous river in England.",
                    hint_hi: "यह इंग्लैंड की एक बहुत प्रसिद्ध नदी है।",
                    explanation_en: "The River Thames flows through southern England, including London.",
                    explanation_hi: "टेम्स नदी लंदन सहित दक्षिणी इंग्लैंड से होकर बहती है।",
                    difficulty: "medium"
                },
                {
                    q_en: "Which country has the largest population in the world?",
                    q_hi: "दुनिया में सबसे अधिक जनसंख्या वाला देश कौन सा है?",
                    options_en: ["China", "India", "USA", "Indonesia"],
                    options_hi: ["चीन", "भारत", "यूएसए", "इंडोनेशिया"],
                    answer: 1,
                    hint_en: "As of 2023, it has surpassed China.",
                    hint_hi: "2023 तक, इसने चीन को पीछे छोड़ दिया है।",
                    explanation_en: "India is currently the most populous country in the world.",
                    explanation_hi: "भारत वर्तमान में दुनिया का सबसे अधिक जनसंख्या वाला देश है।",
                    difficulty: "easy"
                },
                {
                    q_en: "What is the capital of Italy?",
                    q_hi: "इटली की राजधानी क्या है?",
                    options_en: ["Venice", "Milan", "Rome", "Florence"],
                    options_hi: ["वेनिस", "मिलान", "रोम", "फ्लोरेंस"],
                    answer: 2,
                    hint_en: "It is often called the 'Eternal City'.",
                    hint_hi: "इसे अक्सर 'शाश्वत शहर' कहा जाता है।",
                    explanation_en: "Rome is the capital city of Italy and also of the Lazio region.",
                    explanation_hi: "रोम इटली की और लाज़ियो क्षेत्र की भी राजधानी है।",
                    difficulty: "easy"
                },
                {
                    q_en: "Which desert is located in India?",
                    q_hi: "भारत में कौन सा रेगिस्तान स्थित है?",
                    options_en: ["Sahara", "Gobi", "Thar", "Atacama"],
                    options_hi: ["सहारा", "गोबी", "थार", "अटाकामा"],
                    answer: 2,
                    hint_en: "It is also known as the Great Indian Desert.",
                    hint_hi: "इसे ग्रेट इंडियन डेजर्ट के नाम से भी जाना जाता है।",
                    explanation_en: "The Thar Desert forms a natural boundary between India and Pakistan.",
                    explanation_hi: "थार मरुस्थल भारत और पाकिस्तान के बीच एक प्राकृतिक सीमा बनाता है।",
                    difficulty: "easy"
                },
                {
                    q_en: "How many states are there in India?",
                    q_hi: "भारत में कितने राज्य हैं?",
                    options_en: ["27", "28", "29", "30"],
                    options_hi: ["27", "28", "29", "30"],
                    answer: 1,
                    hint_en: "The number changed after Jammu and Kashmir became a Union Territory.",
                    hint_hi: "जम्मू और कश्मीर के केंद्र शासित प्रदेश बनने के बाद संख्या बदल गई।",
                    explanation_en: "India currently has 28 states and 8 Union Territories.",
                    explanation_hi: "भारत में वर्तमान में 28 राज्य और 8 केंद्र शासित प्रदेश हैं।",
                    difficulty: "medium"
                },
                {
                    q_en: "Which is the deepest point in the world's oceans?",
                    q_hi: "दुनिया के महासागरों में सबसे गहरा बिंदु कौन सा है?",
                    options_en: ["Java Trench", "Mariana Trench", "Puerto Rico Trench", "Tonga Trench"],
                    options_hi: ["जावा ट्रेंच", "मारियाना ट्रेंच", "प्यूर्टो रिको ट्रेंच", "टोंगा ट्रेंच"],
                    answer: 1,
                    hint_en: "It is located in the Pacific Ocean.",
                    hint_hi: "यह प्रशांत महासागर में स्थित है।",
                    explanation_en: "The Mariana Trench is the deepest part of the world's oceans.",
                    explanation_hi: "मारियाना ट्रेंच दुनिया के महासागरों का सबसे गहरा हिस्सा है।",
                    difficulty: "hard"
                },
                {
                    q_en: "Which country is known as the 'Land of a Thousand Lakes'?",
                    q_hi: "किस देश को 'हजारों झीलों की भूमि' के रूप में जाना जाता है?",
                    options_en: ["Norway", "Sweden", "Finland", "Canada"],
                    options_hi: ["नार्वे", "स्वीडन", "फिनलैंड", "कनाडा"],
                    answer: 2,
                    hint_en: "It's a Nordic country in Northern Europe.",
                    hint_hi: "यह उत्तरी यूरोप का एक नॉर्डिक देश है।",
                    explanation_en: "Finland has about 188,000 lakes.",
                    explanation_hi: "फिनलैंड में लगभग 188,000 झीलें हैं।",
                    difficulty: "medium"
                },
                {
                    q_en: "What is the capital of the United States?",
                    q_hi: "संयुक्त राज्य अमेरिका की राजधानी क्या है?",
                    options_en: ["New York City", "Los Angeles", "Chicago", "Washington D.C."],
                    options_hi: ["न्यूयॉर्क सिटी", "लॉस एंजिल्स", "शिकागो", "वाशिंगटन डी.सी."],
                    answer: 3,
                    hint_en: "It is named after the first US President.",
                    hint_hi: "इसका नाम पहले अमेरिकी राष्ट्रपति के नाम पर रखा गया है।",
                    explanation_en: "Washington, D.C. is the capital city of the United States of America.",
                    explanation_hi: "वाशिंगटन, डी.सी. संयुक्त राज्य अमेरिका की राजधानी है।",
                    difficulty: "easy"
                },
                {
                    q_en: "Which is the largest lake in the world?",
                    q_hi: "दुनिया की सबसे बड़ी झील कौन सी है?",
                    options_en: ["Lake Superior", "Caspian Sea", "Lake Victoria", "Lake Baikal"],
                    options_hi: ["सुपीरियर झील", "कैस्पियन सागर", "विक्टोरिया झील", "बैकाल झील"],
                    answer: 1,
                    hint_en: "Despite its name, it is a lake.",
                    hint_hi: "इसके नाम के बावजूद, यह एक झील है।",
                    explanation_en: "The Caspian Sea is the world's largest inland body of water.",
                    explanation_hi: "कैस्पियन सागर दुनिया का सबसे बड़ा अंतर्देशीय जल निकाय है।",
                    difficulty: "hard"
                }
            ],
            2: [], 3: [], 4: [], 5: [], 6: []
        }
    }
};

