const quizData = {
    gk: {
        title_en: "General Knowledge",
        title_hi: "सामान्य ज्ञान",
        sections: {
            1: [
                {
                    q_en: "Which is the largest organ in the human body?",
                    q_hi: "मानव शरीर का सबसे बड़ा अंग कौन सा है?",
                    options_en: ["Liver", "Heart", "Skin", "Brain"],
                    options_hi: ["यकृत", "हृदय", "त्वचा", "मस्तिष्क"],
                    answer: 2,
                    hint_en: "It covers your entire body.",
                    hint_hi: "यह आपके पूरे शरीर को ढकता है।",
                    explanation_en: "The skin is the largest organ of the body, covering about 2 square meters.",
                    explanation_hi: "त्वचा शरीर का सबसे बड़ा अंग है, जो लगभग 2 वर्ग मीटर को कवर करती है।",
                    difficulty: "easy"
                },
                {
                    q_en: "Who is known as the 'Iron Man of India'?",
                    q_hi: "भारत के 'लौह पुरुष' के रूप में किसे जाना जाता है?",
                    options_en: ["Mahatma Gandhi", "Jawaharlal Nehru", "Sardar Vallabhbhai Patel", "Subhash Chandra Bose"],
                    options_hi: ["महात्मा गांधी", "जवाहरलाल नेहरू", "सरदार वल्लभभाई पटेल", "सुभाष चंद्र बोस"],
                    answer: 2,
                    hint_en: "He was the first Deputy Prime Minister of India.",
                    hint_hi: "वे भारत के पहले उप प्रधानमंत्री थे।",
                    explanation_en: "Sardar Patel is called the Iron Man of India for his role in integrating princely states.",
                    explanation_hi: "रियासतों के एकीकरण में उनकी भूमिका के लिए सरदार पटेल को भारत का लौह पुरुष कहा जाता है।",
                    difficulty: "medium"
                },
                {
                    q_en: "What is the currency of Japan?",
                    q_hi: "जापान की मुद्रा क्या है?",
                    options_en: ["Yuan", "Yen", "Won", "Baht"],
                    options_hi: ["युआन", "येन", "वोन", "बहत"],
                    answer: 1,
                    hint_en: "It starts with 'Y'.",
                    hint_hi: "यह 'Y' से शुरू होता है।",
                    explanation_en: "The Yen is the official currency of Japan and the third most traded currency.",
                    explanation_hi: "येन जापान की आधिकारिक मुद्रा है और तीसरी सबसे अधिक कारोबार वाली मुद्रा है।",
                    difficulty: "easy"
                },
                {
                    q_en: "Identify this famous landmark:",
                    q_hi: "इस प्रसिद्ध स्थल को पहचानें:",
                    options_en: ["Eiffel Tower", "Taj Mahal", "Great Wall of China", "Statue of Liberty"],
                    options_hi: ["एफिल टॉवर", "ताज महल", "चीन की महान दीवार", "स्टैच्यू ऑफ लिबर्टी"],
                    answer: 1,
                    hint_en: "It is located in Agra, India.",
                    hint_hi: "यह आगरा, भारत में स्थित है।",
                    explanation_en: "The Taj Mahal is an ivory-white marble mausoleum on the right bank of the river Yamuna.",
                    explanation_hi: "ताजमहल यमुना नदी के दाहिने किनारे पर एक हाथीदांत-सफेद संगमरमर का मकबरा है।",
                    difficulty: "easy",
                    img: "https://images.unsplash.com/photo-1564507592333-c60657eea023?auto=format&fit=crop&w=400&q=80"
                },
                {
                    q_en: "Which planet is known as the 'Red Planet'?",
                    q_hi: "किस ग्रह को 'लाल ग्रह' के रूप में जाना जाता है?",
                    options_en: ["Venus", "Mars", "Jupiter", "Saturn"],
                    options_hi: ["शुक्र", "मंगल", "बृहस्पति", "शनि"],
                    answer: 1,
                    hint_en: "It is the fourth planet from the Sun.",
                    hint_hi: "यह सूर्य से चौथा ग्रह है।",
                    explanation_en: "Mars is known as the Red Planet because of iron oxide on its surface.",
                    explanation_hi: "सतह पर आयरन ऑक्साइड के कारण मंगल को लाल ग्रह कहा जाता है।",
                    difficulty: "easy"
                },
                {
                    q_en: "Who wrote the Indian National Anthem?",
                    q_hi: "भारत का राष्ट्रगान किसने लिखा था?",
                    options_en: ["Bankim Chandra Chatterjee", "Rabindranath Tagore", "Sarojini Naidu", "Mahatma Gandhi"],
                    options_hi: ["बंकिम चंद्र चटर्जी", "रवींद्रनाथ टैगोर", "सरोजिनी नायडू", "महात्मा गांधी"],
                    answer: 1,
                    hint_en: "He was the first Asian to win a Nobel Prize.",
                    hint_hi: "वे नोबेल पुरस्कार जीतने वाले पहले एशियाई थे।",
                    explanation_en: "Rabindranath Tagore wrote 'Jana Gana Mana' in 1911.",
                    explanation_hi: "रवींद्रनाथ टैगोर ने 1911 में 'जन गण मन' लिखा था।",
                    difficulty: "medium"
                },
                {
                    q_en: "Which is the smallest country in the world?",
                    q_hi: "दुनिया का सबसे छोटा देश कौन सा है?",
                    options_en: ["Monaco", "Vatican City", "San Marino", "Liechtenstein"],
                    options_hi: ["मोनाको", "वेटिकन सिटी", "सैन मैरिनो", "लिकटेंस्टीन"],
                    answer: 1,
                    hint_en: "It is located within the city of Rome.",
                    hint_hi: "यह रोम शहर के भीतर स्थित है।",
                    explanation_en: "Vatican City is the smallest country by both area and population.",
                    explanation_hi: "क्षेत्रफल और जनसंख्या दोनों के मामले में वेटिकन सिटी सबसे छोटा देश है।",
                    difficulty: "medium"
                },
                {
                    q_en: "What is the capital of France?",
                    q_hi: "फ्रांस की राजधानी क्या है?",
                    options_en: ["Berlin", "London", "Madrid", "Paris"],
                    options_hi: ["बर्लिन", "लंदन", "मैड्रिड", "पेरिस"],
                    answer: 3,
                    hint_en: "Known as the City of Light.",
                    hint_hi: "प्रकाश के शहर के रूप में जाना जाता है।",
                    explanation_en: "Paris is the capital and most populous city of France.",
                    explanation_hi: "पेरिस फ्रांस की राजधानी और सबसे अधिक आबादी वाला शहर है।",
                    difficulty: "easy"
                },
                {
                    q_en: "Which is the longest river in the world?",
                    q_hi: "दुनिया की सबसे लंबी नदी कौन सी है?",
                    options_en: ["Amazon", "Nile", "Yangtze", "Mississippi"],
                    options_hi: ["अमेज़न", "नील", "यांग्त्ज़ी", "मिसिसिपी"],
                    answer: 1,
                    hint_en: "It flows through northeastern Africa.",
                    hint_hi: "यह उत्तर-पूर्वी अफ्रीका से होकर बहती है।",
                    explanation_en: "The Nile is traditionally considered the longest river in the world.",
                    explanation_hi: "नील नदी को पारंपरिक रूप से दुनिया की सबसे लंबी नदी माना जाता है।",
                    difficulty: "medium"
                },
                {
                    q_en: "Who invented the telephone?",
                    q_hi: "टेलीफोन का आविष्कार किसने किया था?",
                    options_en: ["Thomas Edison", "Nikola Tesla", "Alexander Graham Bell", "Albert Einstein"],
                    options_hi: ["थॉमस एडिसन", "निकोला टेस्ला", "अलेक्जेंडर ग्राहम बेल", "अल्बर्ट आइंस्टीन"],
                    answer: 2,
                    hint_en: "His last name rhymes with the sound a phone makes.",
                    hint_hi: "उनका उपनाम फोन की आवाज से मिलता-जुलता है।",
                    explanation_en: "Alexander Graham Bell is credited with patenting the first practical telephone.",
                    explanation_hi: "अलेक्जेंडर ग्राहम बेल को पहले व्यावहारिक टेलीफोन के पेटेंट का श्रेय दिया जाता है।",
                    difficulty: "easy"
                },
                {
                    q_en: "Which is the highest mountain peak in India?",
                    q_hi: "भारत की सबसे ऊँची पर्वत चोटी कौन सी है?",
                    options_en: ["Mount Everest", "Kanchenjunga", "Nanda Devi", "K2"],
                    options_hi: ["माउंट एवरेस्ट", "कंचनजंगा", "नंदा देवी", "के2"],
                    answer: 1,
                    hint_en: "It is located in Sikkim.",
                    hint_hi: "यह सिक्किम में स्थित है।",
                    explanation_en: "Kanchenjunga is the highest peak in India and the third highest in the world.",
                    explanation_hi: "कंचनजंगा भारत की सबसे ऊँची और दुनिया की तीसरी सबसे ऊँची चोटी है।",
                    difficulty: "medium"
                },
                {
                    q_en: "Who was the first woman President of India?",
                    q_hi: "भारत की पहली महिला राष्ट्रपति कौन थीं?",
                    options_en: ["Pratibha Patil", "Indira Gandhi", "Sarojini Naidu", "Draupadi Murmu"],
                    options_hi: ["प्रतिभा पाटिल", "इंदिरा गांधी", "सरोजिनी नायडू", "द्रौपदी मुर्मू"],
                    answer: 0,
                    hint_en: "She served from 2007 to 2012.",
                    hint_hi: "उन्होंने 2007 से 2012 तक सेवा की।",
                    explanation_en: "Pratibha Patil was the 12th President of India and the first woman to hold the office.",
                    explanation_hi: "प्रतिभा पाटिल भारत की 12वीं राष्ट्रपति थीं और इस पद पर बैठने वाली पहली महिला थीं।",
                    difficulty: "medium"
                },
                {
                    q_en: "Which is the largest state in India by area?",
                    q_hi: "क्षेत्रफल की दृष्टि से भारत का सबसे बड़ा राज्य कौन सा है?",
                    options_en: ["Madhya Pradesh", "Maharashtra", "Rajasthan", "Uttar Pradesh"],
                    options_hi: ["मध्य प्रदेश", "महाराष्ट्र", "राजस्थान", "उत्तर प्रदेश"],
                    answer: 2,
                    hint_en: "It is known for the Thar Desert.",
                    hint_hi: "यह थार मरुस्थल के लिए जाना जाता है।",
                    explanation_en: "Rajasthan is the largest Indian state by area, covering about 10.4% of India.",
                    explanation_hi: "राजस्थान क्षेत्रफल के हिसाब से सबसे बड़ा भारतीय राज्य है, जो भारत के लगभग 10.4% हिस्से को कवर करता है।",
                    difficulty: "easy"
                },
                {
                    q_en: "Which is the smallest state in India by area?",
                    q_hi: "क्षेत्रफल की दृष्टि से भारत का सबसे छोटा राज्य कौन सा है?",
                    options_en: ["Sikkim", "Goa", "Tripura", "Manipur"],
                    options_hi: ["सिक्किम", "गोवा", "त्रिपुरा", "मणिपुर"],
                    answer: 1,
                    hint_en: "Famous for its beaches.",
                    hint_hi: "अपने समुद्र तटों के लिए प्रसिद्ध।",
                    explanation_en: "Goa is India's smallest state by area and has the highest GDP per capita.",
                    explanation_hi: "गोवा क्षेत्रफल के हिसाब से भारत का सबसे छोटा राज्य है और इसकी प्रति व्यक्ति जीडीपी सबसे अधिक है।",
                    difficulty: "easy"
                },
                {
                    q_en: "Which city is known as the 'Silicon Valley of India'?",
                    q_hi: "किस शहर को 'भारत की सिलिकॉन वैली' के रूप में जाना जाता है?",
                    options_en: ["Hyderabad", "Pune", "Bengaluru", "Chennai"],
                    options_hi: ["हैदराबाद", "पुणे", "बेंगलुरु", "चेन्नई"],
                    answer: 2,
                    hint_en: "It is the capital of Karnataka.",
                    hint_hi: "यह कर्नाटक की राजधानी है।",
                    explanation_en: "Bengaluru is called the Silicon Valley of India because of its role as the nation's leading IT exporter.",
                    explanation_hi: "बेंगलुरु को राष्ट्र के प्रमुख आईटी निर्यातक के रूप में इसकी भूमिका के कारण भारत की सिलिकॉन वैली कहा जाता है।",
                    difficulty: "easy"
                },
                {
                    q_en: "What is the national bird of India?",
                    q_hi: "भारत का राष्ट्रीय पक्षी क्या है?",
                    options_en: ["Sparrow", "Eagle", "Peacock", "Parrot"],
                    options_hi: ["गौरैया", "बाज", "मोर", "तोता"],
                    answer: 2,
                    hint_en: "It has colorful feathers and dances in the rain.",
                    hint_hi: "इसके रंगीन पंख होते हैं और यह बारिश में नाचता है।",
                    explanation_en: "The Indian Peacock was declared the national bird of India in 1963.",
                    explanation_hi: "भारतीय मोर को 1963 में भारत का राष्ट्रीय पक्षी घोषित किया गया था।",
                    difficulty: "easy"
                },
                {
                    q_en: "What is the national animal of India?",
                    q_hi: "भारत का राष्ट्रीय पशु क्या है?",
                    options_en: ["Lion", "Tiger", "Elephant", "Leopard"],
                    options_hi: ["शेर", "बाघ", "हाथी", "तेंदुआ"],
                    answer: 1,
                    hint_en: "Known for its stripes.",
                    hint_hi: "अपनी धारियों के लिए जाना जाता है।",
                    explanation_en: "The Bengal Tiger is the national animal of India.",
                    explanation_hi: "बंगाल टाइगर भारत का राष्ट्रीय पशु है।",
                    difficulty: "easy"
                },
                {
                    q_en: "What is the national flower of India?",
                    q_hi: "भारत का राष्ट्रीय फूल क्या है?",
                    options_en: ["Rose", "Lotus", "Sunflower", "Marigold"],
                    options_hi: ["गुलाब", "कमल", "सूरजमुखी", "गेंदा"],
                    answer: 1,
                    hint_en: "It grows in muddy water.",
                    hint_hi: "यह कीचड़ भरे पानी में उगता है।",
                    explanation_en: "The Lotus is the national flower of India, symbolizing purity and auspiciousness.",
                    explanation_hi: "कमल भारत का राष्ट्रीय फूल है, जो पवित्रता और शुभता का प्रतीक है।",
                    difficulty: "easy"
                },
                {
                    q_en: "What is the national fruit of India?",
                    q_hi: "भारत का राष्ट्रीय फल क्या है?",
                    options_en: ["Apple", "Banana", "Mango", "Orange"],
                    options_hi: ["सेब", "केला", "आम", "संतरा"],
                    answer: 2,
                    hint_en: "Known as the King of Fruits.",
                    hint_hi: "फलों के राजा के रूप में जाना जाता है।",
                    explanation_en: "Mango is the national fruit of India.",
                    explanation_hi: "आम भारत का राष्ट्रीय फल है।",
                    difficulty: "easy"
                },
                {
                    q_en: "What is the national tree of India?",
                    q_hi: "भारत का राष्ट्रीय वृक्ष क्या है?",
                    options_en: ["Neem", "Peepal", "Banyan", "Mango Tree"],
                    options_hi: ["नीम", "पीपल", "बरगद", "आम का पेड़"],
                    answer: 2,
                    hint_en: "It has hanging roots.",
                    hint_hi: "इसकी लटकती हुई जड़ें होती हैं।",
                    explanation_en: "The Banyan tree is the national tree of India.",
                    explanation_hi: "बरगद का पेड़ भारत का राष्ट्रीय वृक्ष है।",
                    difficulty: "easy"
                },
                {
                    q_en: "Who was the first Indian to win a Nobel Prize?",
                    q_hi: "नोबेल पुरस्कार जीतने वाले पहले भारतीय कौन थे?",
                    options_en: ["C.V. Raman", "Mother Teresa", "Rabindranath Tagore", "Hargobind Khorana"],
                    options_hi: ["सी.वी. रमन", "मदर टेरेसा", "रवींद्रनाथ टैगोर", "हरगोविंद खुराना"],
                    answer: 2,
                    hint_en: "He won it for Literature in 1913.",
                    hint_hi: "उन्होंने 1913 में साहित्य के लिए इसे जीता था।",
                    explanation_en: "Rabindranath Tagore won the Nobel Prize for Literature for his collection 'Gitanjali'.",
                    explanation_hi: "रवींद्रनाथ टैगोर ने अपने संग्रह 'गीतांजलि' के लिए साहित्य का नोबेल पुरस्कार जीता।",
                    difficulty: "medium"
                },
                {
                    q_en: "Who is known as the 'Missile Man of India'?",
                    q_hi: "भारत के 'मिसाइल मैन' के रूप में किसे जाना जाता है?",
                    options_en: ["Vikram Sarabhai", "Homi J. Bhabha", "A.P.J. Abdul Kalam", "Satish Dhawan"],
                    options_hi: ["विक्रम साराभाई", "होमी जे. भाभा", "ए.पी.जे. अब्दुल कलाम", "सतीश धवन"],
                    answer: 2,
                    hint_en: "He was also the 11th President of India.",
                    hint_hi: "वे भारत के 11वें राष्ट्रपति भी थे।",
                    explanation_en: "Dr. A.P.J. Abdul Kalam is called the Missile Man for his work on ballistic missile technology.",
                    explanation_hi: "डॉ. ए.पी.जे. अब्दुल कलाम को बैलिस्टिक मिसाइल तकनीक पर उनके काम के लिए मिसाइल मैन कहा जाता है।",
                    difficulty: "easy"
                },
                {
                    q_en: "Which state is known as the 'Spices Garden of India'?",
                    q_hi: "किस राज्य को 'भारत का मसालों का बगीचा' कहा जाता है?",
                    options_en: ["Karnataka", "Kerala", "Tamil Nadu", "Andhra Pradesh"],
                    options_hi: ["कर्नाटक", "केरल", "तमिलनाडु", "आंध्र प्रदेश"],
                    answer: 1,
                    hint_en: "It is located on the Malabar Coast.",
                    hint_hi: "यह मालाबार तट पर स्थित है।",
                    explanation_en: "Kerala is known as the Spice Garden of India for its variety of spices.",
                    explanation_hi: "केरल अपनी विभिन्न प्रकार के मसालों के लिए भारत के मसालों के बगीचे के रूप में जाना जाता है।",
                    difficulty: "easy"
                },
                {
                    q_en: "Which is the largest freshwater lake in India?",
                    q_hi: "भारत की सबसे बड़ी मीठे पानी की झील कौन सी है?",
                    options_en: ["Chilika Lake", "Wular Lake", "Dal Lake", "Pulicat Lake"],
                    options_hi: ["चिल्का झील", "वुलर झील", "डल झील", "पुलिकट झील"],
                    answer: 1,
                    hint_en: "It is located in Jammu and Kashmir.",
                    hint_hi: "यह जम्मू और कश्मीर में स्थित है।",
                    explanation_en: "Wular Lake in Jammu and Kashmir is one of the largest freshwater lakes in Asia.",
                    explanation_hi: "जम्मू-कश्मीर की वुलर झील एशिया की सबसे बड़ी मीठे पानी की झीलों में से एक है।",
                    difficulty: "medium"
                },
                {
                    q_en: "Which is the highest dam in India?",
                    q_hi: "भारत का सबसे ऊँचा बाँध कौन सा है?",
                    options_en: ["Bhakra Dam", "Tehri Dam", "Hirakud Dam", "Sardar Sarovar Dam"],
                    options_hi: ["भाखड़ा बाँध", "टिहरी बाँध", "हीराकुंड बाँध", "सरदार सरोवर बाँध"],
                    answer: 1,
                    hint_en: "It is built on the Bhagirathi River.",
                    hint_hi: "यह भागीरथी नदी पर बना है।",
                    explanation_en: "The Tehri Dam in Uttarakhand is the highest dam in India.",
                    explanation_hi: "उत्तराखंड में टिहरी बाँध भारत का सबसे ऊँचा बाँध है।",
                    difficulty: "medium"
                },
                {
                    q_en: "Which is the longest dam in India?",
                    q_hi: "भारत का सबसे लंबा बाँध कौन सा है?",
                    options_en: ["Bhakra Dam", "Tehri Dam", "Hirakud Dam", "Nagarjuna Sagar Dam"],
                    options_hi: ["भाखड़ा बाँध", "टिहरी बाँध", "हीराकुंड बाँध", "नागार्जुन सागर बाँध"],
                    answer: 2,
                    hint_en: "It is built on the Mahanadi River in Odisha.",
                    hint_hi: "यह ओडिशा में महानदी पर बना है।",
                    explanation_en: "Hirakud Dam is the longest earthen dam in the world and the longest dam in India.",
                    explanation_hi: "हीराकुंड बाँध दुनिया का सबसे लंबा मिट्टी का बाँध और भारत का सबसे लंबा बाँध है।",
                    difficulty: "medium"
                },
                {
                    q_en: "Who was the first Indian woman to go into space?",
                    q_hi: "अंतरिक्ष में जाने वाली पहली भारतीय महिला कौन थीं?",
                    options_en: ["Sunita Williams", "Kalpana Chawla", "Anshula Rao", "Santhosh Yadav"],
                    options_hi: ["सुनीता विलियम्स", "कल्पना चावला", "अंशुला राव", "संतोष यादव"],
                    answer: 1,
                    hint_en: "She was born in Karnal, Haryana.",
                    hint_hi: "उनका जन्म करनाल, हरियाणा में हुआ था।",
                    explanation_en: "Kalpana Chawla was the first Indian-born woman to fly in space in 1997.",
                    explanation_hi: "कल्पना चावला 1997 में अंतरिक्ष में उड़ान भरने वाली पहली भारतीय मूल की महिला थीं।",
                    difficulty: "easy"
                },
                {
                    q_en: "Who was the first Indian woman to climb Mount Everest?",
                    q_hi: "माउंट एवरेस्ट पर चढ़ने वाली पहली भारतीय महिला कौन थीं?",
                    options_en: ["Santosh Yadav", "Arunima Sinha", "Bachendri Pal", "Premlata Agarwal"],
                    options_hi: ["संतोष यादव", "अरुणिमा सिन्हा", "बछेंद्री पाल", "प्रेमलता अग्रवाल"],
                    answer: 2,
                    hint_en: "She achieved this feat in 1984.",
                    hint_hi: "उन्होंने यह उपलब्धि 1984 में हासिल की थी।",
                    explanation_en: "Bachendri Pal became the first Indian woman to reach the summit of Mt. Everest.",
                    explanation_hi: "बछेंद्री पाल माउंट एवरेस्ट के शिखर पर पहुँचने वाली पहली भारतीय महिला बनीं।",
                    difficulty: "medium"
                },
                {
                    q_en: "Who was the first Governor-General of India?",
                    q_hi: "भारत के पहले गवर्नर-जनरल कौन थे?",
                    options_en: ["Lord Canning", "Lord William Bentinck", "Lord Mountbatten", "Warren Hastings"],
                    options_hi: ["लॉर्ड कैनिंग", "लॉर्ड विलियम बेंटिक", "लॉर्ड माउंटबेटन", "वॉरेन हेस्टिंग्स"],
                    answer: 1,
                    hint_en: "He introduced English education in India.",
                    hint_hi: "उन्होंने भारत में अंग्रेजी शिक्षा की शुरुआत की थी।",
                    explanation_en: "Lord William Bentinck was the first Governor-General of India (1833-1835).",
                    explanation_hi: "लॉर्ड विलियम बेंटिक भारत के पहले गवर्नर-जनरल (1833-1835) थे।",
                    difficulty: "hard"
                },
                {
                    q_en: "Who founded the Brahmo Samaj?",
                    q_hi: "ब्रह्म समाज की स्थापना किसने की थी?",
                    options_en: ["Swami Vivekananda", "Dayanand Saraswati", "Raja Ram Mohan Roy", "Ishwar Chandra Vidyasagar"],
                    options_hi: ["स्वामी विवेकानंद", "दयानंद सरस्वती", "राजा राम मोहन राय", "ईश्वर चंद्र विद्यासागर"],
                    answer: 2,
                    hint_en: "He is known as the 'Father of Modern India'.",
                    hint_hi: "उन्हें 'आधुनिक भारत के पिता' के रूप में जाना जाता है।",
                    explanation_en: "Raja Ram Mohan Roy founded the Brahmo Samaj in 1828 in Calcutta.",
                    explanation_hi: "राजा राम मोहन राय ने 1828 में कलकत्ता में ब्रह्म समाज की स्थापना की थी।",
                    difficulty: "medium"
                },
                {
                    q_en: "Which is the oldest mountain range in India?",
                    q_hi: "भारत की सबसे पुरानी पर्वत श्रृंखला कौन सी है?",
                    options_en: ["Himalayas", "Vindhyas", "Aravalli Range", "Satpura Range"],
                    options_hi: ["हिमालय", "विंध्य", "अरावली पर्वतमाला", "सतपुड़ा पर्वतमाला"],
                    answer: 2,
                    hint_en: "It runs through Rajasthan and Haryana.",
                    hint_hi: "यह राजस्थान और हरियाणा से होकर गुजरती है।",
                    explanation_en: "The Aravalli Range is the oldest fold mountain system in India.",
                    explanation_hi: "अरावली पर्वतमाला भारत की सबसे पुरानी वलित पर्वत प्रणाली है।",
                    difficulty: "medium"
                },
                {
                    q_en: "What is the total number of states in India currently?",
                    q_hi: "वर्तमान में भारत में राज्यों की कुल संख्या कितनी है?",
                    options_en: ["27", "28", "29", "30"],
                    options_hi: ["27", "28", "29", "30"],
                    answer: 1,
                    hint_en: "Jammu and Kashmir is now a Union Territory.",
                    hint_hi: "जम्मू और कश्मीर अब एक केंद्र शासित प्रदेश है।",
                    explanation_en: "As of 2024, India has 28 states and 8 Union Territories.",
                    explanation_hi: "2024 तक, भारत में 28 राज्य और 8 केंद्र शासित प्रदेश हैं।",
                    difficulty: "easy"
                },
                {
                    q_en: "How many Union Territories are there in India?",
                    q_hi: "भारत में कितने केंद्र शासित प्रदेश हैं?",
                    options_en: ["7", "8", "9", "6"],
                    options_hi: ["7", "8", "9", "6"],
                    answer: 1,
                    hint_en: "Daman & Diu and Dadra & Nagar Haveli were merged.",
                    hint_hi: "दमन और दीव और दादरा और नगर हवेली का विलय कर दिया गया था।",
                    explanation_en: "India has 8 Union Territories as of 2024.",
                    explanation_hi: "2024 तक भारत में 8 केंद्र शासित प्रदेश हैं।",
                    difficulty: "easy"
                },
                {
                    q_en: "Which river is known as the 'Dakshin Ganga'?",
                    q_hi: "किस नदी को 'दक्षिण गंगा' के रूप में जाना जाता है?",
                    options_en: ["Krishna", "Cauvery", "Godavari", "Mahanadi"],
                    options_hi: ["कृष्णा", "कावेरी", "गोदावरी", "महानदी"],
                    answer: 2,
                    hint_en: "It is the second longest river in India.",
                    hint_hi: "यह भारत की दूसरी सबसे लंबी नदी है।",
                    explanation_en: "The Godavari is often referred to as Dakshin Ganga due to its size and length.",
                    explanation_hi: "गोदावरी को उसके आकार और लंबाई के कारण अक्सर दक्षिण गंगा कहा जाता है।",
                    difficulty: "medium"
                },
                {
                    q_en: "Where is the largest museum in India located?",
                    q_hi: "भारत का सबसे बड़ा संग्रहालय कहाँ स्थित है?",
                    options_en: ["Delhi", "Mumbai", "Kolkata", "Chennai"],
                    options_hi: ["दिल्ली", "मुंबई", "कोलकाता", "चेन्नई"],
                    answer: 2,
                    hint_en: "It was founded in 1814.",
                    hint_hi: "इसकी स्थापना 1814 में हुई थी।",
                    explanation_en: "The Indian Museum in Kolkata is the largest and oldest museum in India.",
                    explanation_hi: "कोलकाता में भारतीय संग्रहालय भारत का सबसे बड़ा और सबसे पुराना संग्रहालय है।",
                    difficulty: "medium"
                },
                {
                    q_en: "The Sun Temple is located in which state?",
                    q_hi: "सूर्य मंदिर किस राज्य में स्थित है?",
                    options_en: ["Gujarat", "Odisha", "Tamil Nadu", "Rajasthan"],
                    options_hi: ["गुजरात", "ओडिशा", "तमिलनाडु", "राजस्थान"],
                    answer: 1,
                    hint_en: "It is in Konark.",
                    hint_hi: "यह कोणार्क में है।",
                    explanation_en: "The Konark Sun Temple is a 13th-century Sun Temple in Odisha.",
                    explanation_hi: "कोणार्क सूर्य मंदिर ओडिशा में 13वीं शताब्दी का सूर्य मंदिर है।",
                    difficulty: "easy"
                },
                {
                    q_en: "Gateway of India is located in which city?",
                    q_hi: "गेटवे ऑफ इंडिया किस शहर में स्थित है?",
                    options_en: ["New Delhi", "Mumbai", "Kolkata", "Hyderabad"],
                    options_hi: ["नई दिल्ली", "मुंबई", "कोलकाता", "हैदराबाद"],
                    answer: 1,
                    hint_en: "It faces the Arabian Sea.",
                    hint_hi: "यह अरब सागर की ओर है।",
                    explanation_en: "The Gateway of India was built to commemorate the visit of King George V to Mumbai.",
                    explanation_hi: "गेटवे ऑफ इंडिया का निर्माण राजा जॉर्ज पंचम की मुंबई यात्रा की याद में किया गया था।",
                    difficulty: "easy"
                },
                {
                    q_en: "India Gate is located in which city?",
                    q_hi: "इंडिया गेट किस शहर में स्थित है?",
                    options_en: ["Mumbai", "Kolkata", "New Delhi", "Agra"],
                    options_hi: ["मुंबई", "कोलकाता", "नई दिल्ली", "आगरा"],
                    answer: 2,
                    hint_en: "It is a war memorial.",
                    hint_hi: "यह एक युद्ध स्मारक है।",
                    explanation_en: "India Gate is a memorial to 70,000 soldiers of the British Indian Army who died in WWI.",
                    explanation_hi: "इंडिया गेट ब्रिटिश भारतीय सेना के 70,000 सैनिकों का स्मारक है जो प्रथम विश्व युद्ध में मारे गए थे।",
                    difficulty: "easy"
                },
                {
                    q_en: "Who was the first Prime Minister of India?",
                    q_hi: "भारत के पहले प्रधानमंत्री कौन थे?",
                    options_en: ["Lal Bahadur Shastri", "Jawaharlal Nehru", "Indira Gandhi", "Gulzarilal Nanda"],
                    options_hi: ["लाल बहादुर शास्त्री", "जवाहरलाल नेहरू", "इंदिरा गांधी", "गुलजारीलाल नंदा"],
                    answer: 1,
                    hint_en: "His birthday is celebrated as Children's Day.",
                    hint_hi: "उनका जन्मदिन बाल दिवस के रूप में मनाया जाता है।",
                    explanation_en: "Jawaharlal Nehru served as the first Prime Minister of independent India.",
                    explanation_hi: "जवाहरलाल नेहरू ने स्वतंत्र भारत के पहले प्रधानमंत्री के रूप में कार्य किया।",
                    difficulty: "easy"
                },
                {
                    q_en: "Who is known as the 'Father of the Indian Constitution'?",
                    q_hi: "भारतीय संविधान के जनक के रूप में किसे जाना जाता है?",
                    options_en: ["Mahatma Gandhi", "Jawaharlal Nehru", "Dr. B.R. Ambedkar", "Sardar Patel"],
                    options_hi: ["महात्मा गांधी", "जवाहरलाल नेहरू", "डॉ. बी.आर. अंबेडकर", "सरदार पटेल"],
                    answer: 2,
                    hint_en: "He was the chairman of the Drafting Committee.",
                    hint_hi: "वे मसौदा समिति के अध्यक्ष थे।",
                    explanation_en: "Dr. B.R. Ambedkar was the chief architect of the Constitution of India.",
                    explanation_hi: "डॉ. बी.आर. अंबेडकर भारत के संविधान के मुख्य वास्तुकार थे।",
                    difficulty: "easy"
                },
                {
                    q_en: "Fundamental Rights are mentioned in which part of the Indian Constitution?",
                    q_hi: "भारतीय संविधान के किस भाग में मौलिक अधिकारों का उल्लेख है?",
                    options_en: ["Part II", "Part III", "Part IV", "Part V"],
                    options_hi: ["भाग II", "भाग III", "भाग IV", "भाग V"],
                    answer: 1,
                    hint_en: "It follows the citizenship section.",
                    hint_hi: "यह नागरिकता अनुभाग के बाद आता है।",
                    explanation_en: "Part III of the Constitution (Articles 12 to 35) deals with Fundamental Rights.",
                    explanation_hi: "संविधान का भाग III (अनुच्छेद 12 से 35) मौलिक अधिकारों से संबंधित है।",
                    difficulty: "hard"
                },
                {
                    q_en: "Which gas is most abundant in the Earth's atmosphere?",
                    q_hi: "पृथ्वी के वायुमंडल में कौन सी गैस सबसे प्रचुर मात्रा में है?",
                    options_en: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Argon"],
                    options_hi: ["ऑक्सीजन", "कार्बन डाइऑक्साइड", "नाइट्रोजन", "आर्गन"],
                    answer: 2,
                    hint_en: "It makes up about 78% of the atmosphere.",
                    hint_hi: "यह वायुमंडल का लगभग 78% हिस्सा बनाता है।",
                    explanation_en: "Nitrogen accounts for about 78.08% of the Earth's atmosphere.",
                    explanation_hi: "पृथ्वी के वायुमंडल में नाइट्रोजन लगभग 78.08% है।",
                    difficulty: "medium"
                },
                {
                    q_en: "Which is the highest civilian award in India?",
                    q_hi: "भारत का सर्वोच्च नागरिक सम्मान कौन सा है?",
                    options_en: ["Padma Vibhushan", "Bharat Ratna", "Param Vir Chakra", "Padma Bhushan"],
                    options_hi: ["पद्म विभूषण", "भारत रत्न", "परमवीर चक्र", "पद्म भूषण"],
                    answer: 1,
                    hint_en: "It is awarded for exceptional service.",
                    hint_hi: "यह असाधारण सेवा के लिए दिया जाता है।",
                    explanation_en: "Bharat Ratna is the highest civilian award of the Republic of India.",
                    explanation_hi: "भारत रत्न भारतीय गणराज्य का सर्वोच्च नागरिक पुरस्कार है।",
                    difficulty: "easy"
                },
                {
                    q_en: "Scurvy is caused by the deficiency of which vitamin?",
                    q_hi: "स्कर्वी किस विटामिन की कमी से होता है?",
                    options_en: ["Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"],
                    options_hi: ["विटामिन ए", "विटामिन बी", "विटामिन सी", "विटामिन डी"],
                    answer: 2,
                    hint_en: "It is found in citrus fruits like lemons.",
                    hint_hi: "यह नींबू जैसे खट्टे फलों में पाया जाता है।",
                    explanation_en: "Scurvy is a disease resulting from a lack of Vitamin C (ascorbic acid).",
                    explanation_hi: "स्कर्वी विटामिन सी (एस्कॉर्बिक एसिड) की कमी से होने वाली बीमारी है।",
                    difficulty: "medium"
                },
                {
                    q_en: "The study of birds is known as?",
                    q_hi: "पक्षियों के अध्ययन को क्या कहा जाता है?",
                    options_en: ["Entomology", "Ornithology", "Ichthyology", "Herpetology"],
                    options_hi: ["कीटविज्ञान", "पक्षीविज्ञान", "मत्स्यविज्ञान", "सरीसृपविज्ञान"],
                    answer: 1,
                    hint_en: "It starts with 'O'.",
                    hint_hi: "यह 'O' से शुरू होता है।",
                    explanation_en: "Ornithology is a branch of zoology that concerns the study of birds.",
                    explanation_hi: "पक्षीविज्ञान (Ornithology) प्राणीशास्त्र की एक शाखा है जो पक्षियों के अध्ययन से संबंधित है।",
                    difficulty: "hard"
                },
                {
                    q_en: "What is the capital of Japan?",
                    q_hi: "जापान की राजधानी क्या है?",
                    options_en: ["Beijing", "Seoul", "Tokyo", "Bangkok"],
                    options_hi: ["बीजिंग", "सियोल", "टोक्यो", "बैंकॉक"],
                    answer: 2,
                    hint_en: "It was formerly known as Edo.",
                    hint_hi: "इसे पहले एदो के नाम से जाना जाता था।",
                    explanation_en: "Tokyo is the capital and largest city of Japan.",
                    explanation_hi: "टोक्यो जापान की राजधानी और सबसे बड़ा शहर है।",
                    difficulty: "easy"
                },
                {
                    q_en: "Which is the largest planet in our solar system?",
                    q_hi: "हमारे सौरमंडल का सबसे बड़ा ग्रह कौन सा है?",
                    options_en: ["Earth", "Saturn", "Jupiter", "Neptune"],
                    options_hi: ["पृथ्वी", "शनि", "बृहस्पति", "वरुण"],
                    answer: 2,
                    hint_en: "It has a Great Red Spot.",
                    hint_hi: "इसमें एक ग्रेट रेड स्पॉट है।",
                    explanation_en: "Jupiter is the largest planet in the solar system, more than twice as massive as all other planets combined.",
                    explanation_hi: "बृहस्पति सौरमंडल का सबसे बड़ा ग्रह है, जो अन्य सभी ग्रहों के संयुक्त द्रव्यमान से दोगुने से भी अधिक विशाल है।",
                    difficulty: "easy"
                },
                {
                    q_en: "What is the currency of the United States of America?",
                    q_hi: "संयुक्त राज्य अमेरिका की मुद्रा क्या है?",
                    options_en: ["Euro", "Pound", "Dollar", "Yen"],
                    options_hi: ["यूरो", "पाउंड", "डॉलर", "येन"],
                    answer: 2,
                    hint_en: "It uses the symbol $. ",
                    hint_hi: "यह $ प्रतीक का उपयोग करता है।",
                    explanation_en: "The United States Dollar is the official currency of the USA.",
                    explanation_hi: "संयुक्त राज्य डॉलर अमेरिका की आधिकारिक मुद्रा है।",
                    difficulty: "easy"
                },
                {
                    q_en: "Which planet is famous for its prominent rings?",
                    q_hi: "कौन सा ग्रह अपने प्रमुख छल्लों के लिए प्रसिद्ध है?",
                    options_en: ["Jupiter", "Saturn", "Uranus", "Mars"],
                    options_hi: ["बृहस्पति", "शनि", "अरुण", "मंगल"],
                    answer: 1,
                    hint_en: "It is the sixth planet from the Sun.",
                    hint_hi: "यह सूर्य से छठा ग्रह है।",
                    explanation_en: "Saturn is best known for its fabulous ring system, made of ice and rock.",
                    explanation_hi: "शनि अपने शानदार वलय तंत्र के लिए जाना जाता है, जो बर्फ और चट्टान से बना है।",
                    difficulty: "easy"
                },
                {
                    q_en: "Which is the largest living animal in the world?",
                    q_hi: "दुनिया का सबसे बड़ा जीवित प्राणी कौन सा है?",
                    options_en: ["Elephant", "Blue Whale", "Giraffe", "Shark"],
                    options_hi: ["हाथी", "ब्लू व्हेल", "जिराफ", "शार्क"],
                    answer: 1,
                    hint_en: "It is a marine mammal.",
                    hint_hi: "यह एक समुद्री स्तनधारी है।",
                    explanation_en: "The Blue Whale is the largest animal known to have ever existed.",
                    explanation_hi: "ब्लू व्हेल अब तक का सबसे बड़ा ज्ञात प्राणी है।",
                    difficulty: "easy"
                }
            ],
            2: [], 3: [], 4: [], 5: [], 6: []
        }
    },
    science: {
        title_en: "Science",
        title_hi: "विज्ञान",
        sections: {
            1: [
                {
                    q_en: "What is the chemical symbol for Water?",
                    q_hi: "पानी का रासायनिक सूत्र क्या है?",
                    options_en: ["O2", "CO2", "H2O", "NaCl"],
                    options_hi: ["O2", "CO2", "H2O", "NaCl"],
                    answer: 2,
                    hint_en: "Two hydrogen atoms and one oxygen atom.",
                    hint_hi: "दो हाइड्रोजन परमाणु और एक ऑक्सीजन परमाणु।",
                    explanation_en: "H2O stands for two Hydrogen atoms and one Oxygen atom.",
                    explanation_hi: "H2O का अर्थ है दो हाइड्रोजन परमाणु और एक ऑक्सीजन परमाणु।",
                    difficulty: "easy"
                },
                {
                    q_en: "Which gas do plants absorb from the atmosphere for photosynthesis?",
                    q_hi: "प्रकाश संश्लेषण के लिए पौधे वायुमंडल से कौन सी गैस अवशोषित करते हैं?",
                    options_en: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"],
                    options_hi: ["ऑक्सीजन", "कार्बन डाइऑक्साइड", "नाइट्रोजन", "हाइड्रोजन"],
                    answer: 1,
                    hint_en: "It is the gas humans breathe out.",
                    hint_hi: "यह वह गैस है जिसे मनुष्य बाहर छोड़ते हैं।",
                    explanation_en: "Plants use Carbon Dioxide and sunlight to produce food.",
                    explanation_hi: "पौधे भोजन बनाने के लिए कार्बन डाइऑक्साइड और सूर्य के प्रकाश का उपयोग करते हैं।",
                    difficulty: "easy"
                },
                {
                    q_en: "What is the power house of the cell?",
                    q_hi: "कोशिका का पावर हाउस किसे कहा जाता है?",
                    options_en: ["Nucleus", "Ribosome", "Mitochondria", "Cytoplasm"],
                    options_hi: ["नाभिक", "राइबोसोम", "माइटोकॉन्ड्रिया", "साइटोप्लाज्म"],
                    answer: 2,
                    hint_en: "It generates energy for the cell.",
                    hint_hi: "यह कोशिका के लिए ऊर्जा उत्पन्न करता है।",
                    explanation_en: "Mitochondria are responsible for creating ATP, the cell's energy currency.",
                    explanation_hi: "माइटोकॉन्ड्रिया एटीपी बनाने के लिए जिम्मेदार हैं, जो कोशिका की ऊर्जा मुद्रा है।",
                    difficulty: "medium"
                },
                {
                    q_en: "Which planet is closest to the Sun?",
                    q_hi: "सूर्य के सबसे निकट कौन सा ग्रह है?",
                    options_en: ["Venus", "Mars", "Mercury", "Earth"],
                    options_hi: ["शुक्र", "मंगल", "बुध", "पृथ्वी"],
                    answer: 2,
                    hint_en: "It's the smallest planet in the solar system.",
                    hint_hi: "यह सौरमंडल का सबसे छोटा ग्रह है।",
                    explanation_en: "Mercury is the closest planet to the Sun and has the shortest orbital period.",
                    explanation_hi: "बुध सूर्य के सबसे निकट का ग्रह है और इसकी कक्षीय अवधि सबसे कम है।",
                    difficulty: "easy"
                },
                {
                    q_en: "What is the hardest natural substance on Earth?",
                    q_hi: "पृथ्वी पर सबसे कठोर प्राकृतिक पदार्थ कौन सा है?",
                    options_en: ["Gold", "Iron", "Diamond", "Platinum"],
                    options_hi: ["सोना", "लोहा", "हीरा", "प्लैटिनम"],
                    answer: 2,
                    hint_en: "It is commonly used in jewelry.",
                    hint_hi: "इसका उपयोग आमतौर पर गहनों में किया जाता है।",
                    explanation_en: "Diamond is the hardest known natural material on Earth.",
                    explanation_hi: "हीरा पृथ्वी पर ज्ञात सबसे कठोर प्राकृतिक पदार्थ है।",
                    difficulty: "medium"
                },
                {
                    q_en: "Which part of the human body produces insulin?",
                    q_hi: "मानव शरीर का कौन सा हिस्सा इंसुलिन पैदा करता है?",
                    options_en: ["Liver", "Pancreas", "Kidney", "Stomach"],
                    options_hi: ["यकृत", "अग्न्याशय", "गुर्दा", "पेट"],
                    answer: 1,
                    hint_en: "Located behind the stomach.",
                    hint_hi: "पेट के पीछे स्थित है।",
                    explanation_en: "The pancreas produces insulin to regulate blood sugar levels.",
                    explanation_hi: "अग्न्याशय रक्त शर्करा के स्तर को नियंत्रित करने के लिए इंसुलिन का उत्पादन करता है।",
                    difficulty: "medium"
                },
                {
                    q_en: "What is the speed of light?",
                    q_hi: "प्रकाश की गति क्या है?",
                    options_en: ["300,000 km/s", "150,000 km/s", "1,000,000 km/s", "500,000 km/s"],
                    options_hi: ["300,000 km/s", "150,000 km/s", "1,000,000 km/s", "500,000 km/s"],
                    answer: 0,
                    hint_en: "It's approximately 3 * 10^8 meters per second.",
                    hint_hi: "यह लगभग 3 * 10^8 मीटर प्रति सेकंड है।",
                    explanation_en: "Light travels at approximately 299,792 kilometers per second in a vacuum.",
                    explanation_hi: "निर्वात में प्रकाश लगभग 299,792 किलोमीटर प्रति सेकंड की गति से चलता है।",
                    difficulty: "hard"
                },
                {
                    q_en: "Who proposed the Theory of Relativity?",
                    q_hi: "सापेक्षता का सिद्धांत किसने प्रस्तावित किया था?",
                    options_en: ["Isaac Newton", "Albert Einstein", "Stephen Hawking", "Galileo Galilei"],
                    options_hi: ["आईजैक न्यूटन", "अल्बर्ट आइंस्टीन", "स्टीफन हॉकिंग", "गैलीलियो गैलीली"],
                    answer: 1,
                    hint_en: "Famous for E=mc^2.",
                    hint_hi: "E=mc^2 के लिए प्रसिद्ध है।",
                    explanation_en: "Albert Einstein developed the special and general theories of relativity.",
                    explanation_hi: "अल्बर्ट आइंस्टीन ने सापेक्षता के विशेष और सामान्य सिद्धांतों को विकसित किया।",
                    difficulty: "medium"
                },
                {
                    q_en: "What is the boiling point of water at sea level?",
                    q_hi: "समुद्र तल पर पानी का क्वथनांक क्या है?",
                    options_en: ["90°C", "100°C", "110°C", "120°C"],
                    options_hi: ["90°C", "100°C", "110°C", "120°C"],
                    answer: 1,
                    hint_en: "It's exactly 100 on the Celsius scale.",
                    hint_hi: "सेल्सियस पैमाने पर यह ठीक 100 है।",
                    explanation_en: "At standard atmospheric pressure, water boils at 100°C.",
                    explanation_hi: "मानक वायुमंडलीय दबाव पर, पानी 100°C पर उबलता है।",
                    difficulty: "easy"
                },
                {
                    q_en: "Which element has the atomic number 1?",
                    q_hi: "किस तत्व की परमाणु संख्या 1 है?",
                    options_en: ["Helium", "Oxygen", "Hydrogen", "Carbon"],
                    options_hi: ["हीलियम", "ऑक्सीजन", "हाइड्रोजन", "कार्बन"],
                    answer: 2,
                    hint_en: "It is the most abundant element in the universe.",
                    hint_hi: "यह ब्रह्मांड में सबसे प्रचुर मात्रा में पाया जाने वाला तत्व है।",
                    explanation_en: "Hydrogen is the first element on the periodic table with one proton.",
                    explanation_hi: "हाइड्रोजन आवर्त सारणी का पहला तत्व है जिसमें एक प्रोटॉन होता है।",
                    difficulty: "medium"
                }
            ],
            2: [], 3: [], 4: [], 5: [], 6: []
        }
    },
    history: {
        title_en: "History",
        title_hi: "इतिहास",
        sections: {
            1: [
                {
                    q_en: "Who was the first President of India?",
                    q_hi: "भारत के पहले राष्ट्रपति कौन थे?",
                    options_en: ["Dr. Rajendra Prasad", "Dr. S. Radhakrishnan", "Zakir Husain", "V.V. Giri"],
                    options_hi: ["डॉ. राजेंद्र प्रसाद", "डॉ. एस. राधाकृष्णन", "ज़ाकिर हुसैन", "वी.वी. गिरी"],
                    answer: 0,
                    hint_en: "He was born in Bihar.",
                    hint_hi: "उनका जन्म बिहार में हुआ था।",
                    explanation_en: "Dr. Rajendra Prasad was the first President of India from 1950 to 1962.",
                    explanation_hi: "डॉ. राजेंद्र प्रसाद 1950 से 1962 तक भारत के पहले राष्ट्रपति थे।",
                    difficulty: "medium"
                },
                {
                    q_en: "In which year did the First World War begin?",
                    q_hi: "प्रथम विश्व युद्ध किस वर्ष शुरू हुआ था?",
                    options_en: ["1912", "1914", "1918", "1939"],
                    options_hi: ["1912", "1914", "1918", "1939"],
                    answer: 1,
                    hint_en: "It started in the early 20th century.",
                    hint_hi: "यह 20वीं सदी की शुरुआत में शुरू हुआ था।",
                    explanation_en: "World War I lasted from 1914 to 1918.",
                    explanation_hi: "प्रथम विश्व युद्ध 1914 से 1918 तक चला था।",
                    difficulty: "medium"
                },
                {
                    q_en: "Who was the founder of the Mughal Empire in India?",
                    q_hi: "भारत में मुगल साम्राज्य का संस्थापक कौन था?",
                    options_en: ["Akbar", "Humayun", "Babur", "Shah Jahan"],
                    options_hi: ["अकबर", "हुमायूँ", "बाबर", "शाहजहाँ"],
                    answer: 2,
                    hint_en: "He won the First Battle of Panipat.",
                    hint_hi: "उन्होंने पानीपत की पहली लड़ाई जीती थी।",
                    explanation_en: "Babur founded the Mughal Empire after defeating Ibrahim Lodi in 1526.",
                    explanation_hi: "बाबर ने 1526 में इब्राहिम लोदी को हराकर मुगल साम्राज्य की स्थापना की थी।",
                    difficulty: "medium"
                },
                {
                    q_en: "Which Indian freedom fighter is known as 'Netaji'?",
                    q_hi: "किस भारतीय स्वतंत्रता सेनानी को 'नेताजी' के नाम से जाना जाता है?",
                    options_en: ["Bhagat Singh", "Subhash Chandra Bose", "Lala Lajpat Rai", "Chandra Shekhar Azad"],
                    options_hi: ["भगत सिंह", "सुभाष चंद्र बोस", "लाला लाजपत राय", "चंद्रशेखर आजाद"],
                    answer: 1,
                    hint_en: "He formed the Indian National Army (INA).",
                    hint_hi: "उन्होंने भारतीय राष्ट्रीय सेना (INA) का गठन किया था।",
                    explanation_en: "Subhash Chandra Bose was given the title Netaji by Indian soldiers in Germany.",
                    explanation_hi: "सुभाष चंद्र बोस को जर्मनी में भारतीय सैनिकों द्वारा नेताजी की उपाधि दी गई थी।",
                    difficulty: "easy"
                },
                {
                    q_en: "In which year did India get independence from British rule?",
                    q_hi: "भारत को ब्रिटिश शासन से स्वतंत्रता किस वर्ष मिली?",
                    options_en: ["1942", "1945", "1947", "1950"],
                    options_hi: ["1942", "1945", "1947", "1950"],
                    answer: 2,
                    hint_en: "It's celebrated every August 15th.",
                    hint_hi: "यह हर 15 अगस्त को मनाया जाता है।",
                    explanation_en: "India became independent on August 15, 1947.",
                    explanation_hi: "भारत 15 अगस्त 1947 को स्वतंत्र हुआ।",
                    difficulty: "easy"
                },
                {
                    q_en: "Who was the first woman Prime Minister of India?",
                    q_hi: "भारत की पहली महिला प्रधानमंत्री कौन थीं?",
                    options_en: ["Pratibha Patil", "Indira Gandhi", "Sushma Swaraj", "Sarojini Naidu"],
                    options_hi: ["प्रतिभा पाटिल", "इंदिरा गांधी", "सुषमा स्वराज", "सरोजिनी नायडू"],
                    answer: 1,
                    hint_en: "She was the daughter of Jawaharlal Nehru.",
                    hint_hi: "वह जवाहरलाल नेहरू की बेटी थीं।",
                    explanation_en: "Indira Gandhi served as Prime Minister from 1966 to 1977 and again from 1980 to 1984.",
                    explanation_hi: "इंदिरा गांधी ने 1966 से 1977 तक और फिर 1980 से 1984 तक प्रधानमंत्री के रूप में कार्य किया।",
                    difficulty: "easy"
                },
                {
                    q_en: "The Quit India Movement was started in which year?",
                    q_hi: "भारत छोड़ो आंदोलन किस वर्ष शुरू किया गया था?",
                    options_en: ["1930", "1942", "1919", "1947"],
                    options_hi: ["1930", "1942", "1919", "1947"],
                    answer: 1,
                    hint_en: "Launched by Mahatma Gandhi during WWII.",
                    hint_hi: "द्वितीय विश्व युद्ध के दौरान महात्मा गांधी द्वारा शुरू किया गया।",
                    explanation_en: "The Quit India Movement was launched on August 8, 1942.",
                    explanation_hi: "भारत छोड़ो आंदोलन 8 अगस्त 1942 को शुरू किया गया था।",
                    difficulty: "medium"
                },
                {
                    q_en: "Who was the first Governor-General of independent India?",
                    q_hi: "स्वतंत्र भारत के पहले गवर्नर-जनरल कौन थे?",
                    options_en: ["Lord Mountbatten", "C. Rajagopalachari", "Jawaharlal Nehru", "Dr. Rajendra Prasad"],
                    options_hi: ["लॉर्ड माउंटबेटन", "सी. राजगोपालाचारी", "जवाहरलाल नेहरू", "डॉ. राजेंद्र प्रसाद"],
                    answer: 0,
                    hint_en: "He was a British statesman.",
                    hint_hi: "वे एक ब्रिटिश राजनेता थे।",
                    explanation_en: "Lord Mountbatten was the last Viceroy and first Governor-General of independent India.",
                    explanation_hi: "लॉर्ड माउंटबेटन अंतिम वायसराय और स्वतंत्र भारत के पहले गवर्नर-जनरल थे।",
                    difficulty: "hard"
                },
                {
                    q_en: "Which emperor built the Sanchi Stupa?",
                    q_hi: "सांची स्तूप का निर्माण किस सम्राट ने करवाया था?",
                    options_en: ["Chandragupta Maurya", "Ashoka", "Kanishka", "Samudragupta"],
                    options_hi: ["चंद्रगुप्त मौर्य", "अशोक", "कनिष्क", "समुद्रगुप्त"],
                    answer: 1,
                    hint_en: "Known for spreading Buddhism.",
                    hint_hi: "बौद्ध धर्म के प्रसार के लिए जाने जाते हैं।",
                    explanation_en: "Emperor Ashoka the Great commissioned the Sanchi Stupa in the 3rd century BCE.",
                    explanation_hi: "सम्राट अशोक महान ने तीसरी शताब्दी ईसा पूर्व में सांची स्तूप का निर्माण करवाया था।",
                    difficulty: "medium"
                },
                {
                    q_en: "Who was the teacher of Alexander the Great?",
                    q_hi: "सिकंदर महान का शिक्षक कौन था?",
                    options_en: ["Socrates", "Plato", "Aristotle", "Pythagoras"],
                    options_hi: ["सुकरात", "प्लेटो", "अरस्तू", "पाइथागोरस"],
                    answer: 2,
                    hint_en: "A famous Greek philosopher.",
                    hint_hi: "एक प्रसिद्ध यूनानी दार्शनिक।",
                    explanation_en: "Aristotle was hired by Philip II of Macedon to tutor Alexander.",
                    explanation_hi: "मैसेडोन के फिलिप द्वितीय ने सिकंदर को ट्यूशन देने के लिए अरस्तू को काम पर रखा था।",
                    difficulty: "hard"
                }
            ],
            2: [], 3: [], 4: [], 5: [], 6: []
        }
    },
    geography: {
        title_en: "Geography",
        title_hi: "भूगोल",
        sections: {
            1: [
                {
                    q_en: "Which is the largest desert in the world?",
                    q_hi: "दुनिया का सबसे बड़ा रेगिस्तान कौन सा है?",
                    options_en: ["Sahara", "Gobi", "Kalahari", "Antarctic Desert"],
                    options_hi: ["सहारा", "गोबी", "कालाहारी", "अंटार्टिक रेगिस्तान"],
                    answer: 3,
                    hint_en: "It's not a hot desert.",
                    hint_hi: "यह गर्म रेगिस्तान नहीं है।",
                    explanation_en: "Antarctica is technically a desert because it receives very little precipitation.",
                    explanation_hi: "अंटार्कटिका तकनीकी रूप से एक रेगिस्तान है क्योंकि वहां बहुत कम वर्षा होती है।",
                    difficulty: "hard"
                },
                {
                    q_en: "Mount Everest is located in which mountain range?",
                    q_hi: "माउंट एवरेस्ट किस पर्वत श्रृंखला में स्थित है?",
                    options_en: ["Andes", "Alps", "Himalayas", "Rockies"],
                    options_hi: ["एंडिस", "आल्प्स", "हिमालय", "रॉकीज"],
                    answer: 2,
                    hint_en: "It is the highest mountain range in the world.",
                    hint_hi: "यह दुनिया की सबसे ऊंची पर्वत श्रृंखला है।",
                    explanation_en: "The Himalayas contain the world's highest peaks, including Everest.",
                    explanation_hi: "हिमालय में एवरेस्ट सहित दुनिया की सबसे ऊंची चोटियाँ हैं।",
                    difficulty: "easy"
                },
                {
                    q_en: "Which is the largest ocean in the world?",
                    q_hi: "दुनिया का सबसे बड़ा महासागर कौन सा है?",
                    options_en: ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Pacific Ocean"],
                    options_hi: ["अटलांटिक महासागर", "हिंद महासागर", "आर्कटिक महासागर", "प्रशांत महासागर"],
                    answer: 3,
                    hint_en: "It covers more than one-third of the Earth's surface.",
                    hint_hi: "यह पृथ्वी की सतह के एक तिहाई से अधिक हिस्से को कवर करता है।",
                    explanation_en: "The Pacific Ocean is the largest and deepest of Earth's oceanic divisions.",
                    explanation_hi: "प्रशांत महासागर पृथ्वी के महासागरीय विभाजनों में सबसे बड़ा और गहरा है।",
                    difficulty: "easy"
                },
                {
                    q_en: "Which country is known as the 'Land of the Rising Sun'?",
                    q_hi: "किस देश को 'उगते सूरज की भूमि' के रूप में जाना जाता है?",
                    options_en: ["China", "Japan", "South Korea", "Thailand"],
                    options_hi: ["चीन", "जापान", "दक्षिण कोरिया", "थाईलैंड"],
                    answer: 1,
                    hint_en: "It's an island nation in East Asia.",
                    hint_hi: "यह पूर्वी एशिया का एक द्वीप देश है।",
                    explanation_en: "Japan is called Nihon in Japanese, which literally means 'sun origin'.",
                    explanation_hi: "जापान को जापानी में निहोन कहा जाता है, जिसका शाब्दिक अर्थ है 'सूर्य की उत्पत्ति' ।",
                    difficulty: "easy"
                },
                {
                    q_en: "Which is the largest continent in the world?",
                    q_hi: "दुनिया का सबसे बड़ा महाद्वीप कौन सा है?",
                    options_en: ["Africa", "North America", "Asia", "Europe"],
                    options_hi: ["अफ्रीका", "उत्तरी अमेरिका", "एशिया", "यूरोप"],
                    answer: 2,
                    hint_en: "It includes countries like India and China.",
                    hint_hi: "इसमें भारत और चीन जैसे देश शामिल हैं।",
                    explanation_en: "Asia is the largest continent in both area and population.",
                    explanation_hi: "एशिया क्षेत्रफल और जनसंख्या दोनों में सबसे बड़ा महाद्वीप है।",
                    difficulty: "easy"
                },
                {
                    q_en: "Which river is known as the 'Life Line of India'?",
                    q_hi: "किस नदी को 'भारत की जीवन रेखा' के रूप में जाना जाता है?",
                    options_en: ["Yamuna", "Ganga", "Brahmaputra", "Godavari"],
                    options_hi: ["यमुना", "गंगा", "ब्रह्मपुत्र", "गोदावरी"],
                    answer: 1,
                    hint_en: "It is the most sacred river for Hindus.",
                    hint_hi: "यह हिंदुओं के लिए सबसे पवित्र नदी है।",
                    explanation_en: "The Ganges (Ganga) is the longest river in India and is considered holy.",
                    explanation_hi: "गंगा भारत की सबसे लंबी नदी है और इसे पवित्र माना जाता है।",
                    difficulty: "easy"
                },
                {
                    q_en: "The equator passes through which of these continents?",
                    q_hi: "भूमध्य रेखा इनमें से किस महाद्वीप से होकर गुजरती है?",
                    options_en: ["Europe", "North America", "Africa", "Antarctica"],
                    options_hi: ["यूरोप", "उत्तरी अमेरिका", "अफ्रीका", "अंटार्कटिका"],
                    answer: 2,
                    hint_en: "This continent is home to the Nile river.",
                    hint_hi: "यह महाद्वीप नील नदी का घर है।",
                    explanation_en: "The Equator passes through Africa, South America, and Asia.",
                    explanation_hi: "भूमध्य रेखा अफ्रीका, दक्षिण अमेरिका और एशिया से होकर गुजरती है।",
                    difficulty: "medium"
                },
                {
                    q_en: "Which city is known as the 'Pink City' of India?",
                    q_hi: "भारत के किस शहर को 'गुलाबी शहर' के रूप में जाना जाता है?",
                    options_en: ["Jodhpur", "Udaipur", "Jaipur", "Bikaner"],
                    options_hi: ["जोधपुर", "उदयपुर", "जयपुर", "बीकानेर"],
                    answer: 2,
                    hint_en: "It's the capital of Rajasthan.",
                    hint_hi: "यह राजस्थान की राजधानी है।",
                    explanation_en: "Jaipur was painted pink to welcome Prince Albert in 1876.",
                    explanation_hi: "1876 में प्रिंस अल्बर्ट के स्वागत के लिए जयपुर को गुलाबी रंग से रंगा गया था।",
                    difficulty: "easy"
                },
                {
                    q_en: "Which is the highest waterfall in the world?",
                    q_hi: "दुनिया का सबसे ऊंचा जलप्रपात कौन सा है?",
                    options_en: ["Niagara Falls", "Victoria Falls", "Angel Falls", "Iguazu Falls"],
                    options_hi: ["नियाग्रा जलप्रपात", "विक्टोरिया जलप्रपात", "एंजेल जलप्रपात", "इगुआज़ु जलप्रपात"],
                    answer: 2,
                    hint_en: "It is located in Venezuela.",
                    hint_hi: "यह वेनेजुएला में स्थित है।",
                    explanation_en: "Angel Falls in Venezuela is the world's highest uninterrupted waterfall.",
                    explanation_hi: "वेनेजुएला में एंजेल जलप्रपात दुनिया का सबसे ऊंचा निर्बाध जलप्रपात है।",
                    difficulty: "medium"
                },
                {
                    q_en: "Which country has the most volcanoes?",
                    q_hi: "किस देश में सबसे अधिक ज्वालामुखी हैं?",
                    options_en: ["Japan", "Iceland", "Indonesia", "USA"],
                    options_hi: ["जापान", "आइसलैंड", "इंडोनेशिया", "यूएसए"],
                    answer: 2,
                    hint_en: "It is an archipelago in Southeast Asia.",
                    hint_hi: "यह दक्षिण पूर्व एशिया में एक द्वीपसमूह है।",
                    explanation_en: "Indonesia has the highest number of active volcanoes in the world.",
                    explanation_hi: "इंडोनेशिया में दुनिया में सबसे अधिक सक्रिय ज्वालामुखी हैं।",
                    difficulty: "hard"
                }
            ],
            2: [], 3: [], 4: [], 5: [], 6: []
        }
    }
};

